apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wuji-dev
resources:
  - namespace.yaml
  - ../../base
labels:
  - pairs:
      wuji.dev/environment: dev
    includeSelectors: false
    includeTemplates: true
