# @generated by datamodel-codegen:
#   filename:  openapi-v2.yaml

from __future__ import annotations

from collections.abc import Mapping as _Mapping
from enum import StrEnum
from typing import Annotated, Any, ClassVar, Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
    model_validator,
)


class _JsonSchemaRuntimeValidationBase(BaseModel):
    __json_schema_unique_items__: ClassVar[tuple[tuple[object, ...], ...]] = ()

    @model_validator(mode='before')
    @classmethod
    def _validate_json_schema_runtime_rules(cls, data: Any) -> Any:
        data = cls._validate_json_schema_unique_items(data)
        return data

    @classmethod
    def _validate_json_schema_unique_items(cls, data: Any) -> Any:
        if not (unique_item_paths := cls.__json_schema_unique_items__):
            return data
        for path in unique_item_paths:
            cls._validate_json_schema_unique_items_path(data, path, 0)
        return data

    @classmethod
    def _validate_json_schema_unique_items_path(
        cls,
        value: Any,
        path: tuple[object, ...],
        position: int,
    ) -> None:
        if position == len(path):
            cls._validate_json_schema_unique_array(value)
            return

        match path[position]:
            case None:
                if not isinstance(value, (list, tuple)):
                    return
                for item in value:
                    cls._validate_json_schema_unique_items_path(item, path, position + 1)
            case ('__json_schema_array_tail__', int() as start):
                if not isinstance(value, (list, tuple)) or start >= len(value):
                    return
                for index in range(start, len(value)):
                    cls._validate_json_schema_unique_items_path(value[index], path, position + 1)
            case int() as index:
                if isinstance(value, (list, tuple)) and index < len(value):
                    cls._validate_json_schema_unique_items_path(value[index], path, position + 1)
            case '__json_schema_mapping_values__':
                if not (isinstance(value, dict) or isinstance(value, _Mapping)):
                    return
                for item in value.values():
                    cls._validate_json_schema_unique_items_path(item, path, position + 1)
            case tuple() as input_names:
                if not (isinstance(value, dict) or isinstance(value, _Mapping)):
                    return
                for name in input_names:
                    if name in value:
                        cls._validate_json_schema_unique_items_path(value[name], path, position + 1)
                        return

    @classmethod
    def _validate_json_schema_unique_array(cls, value: Any) -> None:
        if not isinstance(value, (list, tuple)) or len(value) < 2:
            return

        scalar_items: set[object] | None = None
        structural_items: dict[int, list[Any]] | None = None
        opaque_items: list[Any] | None = None
        for item in value:
            match item:
                case None | bool() | int() | float() | str():
                    item_key = (bool, item) if isinstance(item, bool) else item
                    if scalar_items is None:
                        scalar_items = {item_key}
                    elif item_key in scalar_items:
                        raise ValueError('Array items must be unique')
                    else:
                        scalar_items.add(item_key)
                    if (
                        structural_items is not None
                        and (candidates := structural_items.get(cls._json_schema_unique_items_fingerprint(item)))
                        and any(cls._json_schema_unique_items_equal(item, candidate) for candidate in candidates)
                    ):
                        raise ValueError('Array items must be unique')
                    if (
                        not isinstance(item, bool)
                        and opaque_items is not None
                        and any(
                            cls._json_schema_unique_items_equal_in_either_direction(item, candidate)
                            for candidate in opaque_items
                        )
                    ):
                        raise ValueError('Array items must be unique')
                    continue
                case list() | tuple() | dict() | _Mapping():
                    fingerprint = cls._json_schema_unique_items_fingerprint(item)
                case _:
                    if scalar_items is not None:
                        for scalar_item in scalar_items:
                            scalar_candidate = scalar_item[1] if isinstance(scalar_item, tuple) else scalar_item
                            if not isinstance(scalar_candidate, bool) and cls._json_schema_unique_items_equal_in_either_direction(
                                item, scalar_candidate
                            ):
                                raise ValueError('Array items must be unique')
                    fingerprint = cls._json_schema_unique_items_fingerprint(item)
            if fingerprint is None:
                if structural_items is not None and any(
                    cls._json_schema_unique_items_equal_in_either_direction(item, candidate)
                    for candidates in structural_items.values()
                    for candidate in candidates
                ):
                    raise ValueError('Array items must be unique')
                if opaque_items is not None and any(
                    cls._json_schema_unique_items_equal_in_either_direction(item, candidate)
                    for candidate in opaque_items
                ):
                    raise ValueError('Array items must be unique')
                if opaque_items is None:
                    opaque_items = [item]
                else:
                    opaque_items.append(item)
                continue
            if opaque_items is not None and any(
                cls._json_schema_unique_items_equal_in_either_direction(item, candidate)
                for candidate in opaque_items
            ):
                raise ValueError('Array items must be unique')
            if structural_items is None:
                structural_items = {fingerprint: [item]}
                continue
            if (candidates := structural_items.get(fingerprint)) is None:
                structural_items[fingerprint] = [item]
                continue
            if any(cls._json_schema_unique_items_equal(item, candidate) for candidate in candidates):
                raise ValueError('Array items must be unique')
            candidates.append(item)

    @classmethod
    def _json_schema_unique_items_fingerprint(cls, value: Any) -> int | None:
        match value:
            case None:
                return 0x17
            case bool() as boolean:
                return 0x1F if boolean else 0x1D
            case int() | float() as number:
                return hash(number)
            case str() as string:
                return hash(string)
            case list() | tuple() as array:
                fingerprint = 0x4F
                for item in array:
                    if (item_fingerprint := cls._json_schema_unique_items_fingerprint(item)) is None:
                        return None
                    fingerprint = hash((fingerprint * 1000003) ^ item_fingerprint)
                return hash(fingerprint ^ len(array))
            case dict() | _Mapping() as object_:
                fingerprint = 0x61
                for key, item in object_.items():
                    if (item_fingerprint := cls._json_schema_unique_items_fingerprint(item)) is None:
                        return None
                    fingerprint ^= hash((key, item_fingerprint))
                return hash(fingerprint ^ len(object_))
            case _:
                return cls._json_schema_unique_items_safe_hash(value)

    @classmethod
    def _json_schema_unique_items_equal(cls, left: Any, right: Any) -> bool:
        match left:
            case None:
                return right is None
            case bool() as boolean:
                return isinstance(right, bool) and boolean == right
            case int() | float() as number:
                if isinstance(right, bool):
                    return False
                if isinstance(right, (int, float)):
                    return number == right
                return cls._json_schema_unique_items_safe_equal(number, right)
            case str() as string:
                if isinstance(right, str):
                    return string == right
                return cls._json_schema_unique_items_safe_equal(string, right)
            case list() | tuple() as array:
                return (
                    isinstance(right, (list, tuple))
                    and len(array) == len(right)
                    and all(
                        cls._json_schema_unique_items_equal(item, other)
                        for item, other in zip(array, right, strict=True)
                    )
                )
            case dict() | _Mapping() as object_:
                if not (isinstance(right, dict) or isinstance(right, _Mapping)) or len(object_) != len(right):
                    return False
                return all(
                    key in right and cls._json_schema_unique_items_equal(item, right[key])
                    for key, item in object_.items()
                )
        return cls._json_schema_unique_items_safe_equal(left, right)

    @classmethod
    def _json_schema_unique_items_safe_hash(cls, value: Any) -> int | None:
        try:
            return hash(value)
        except Exception:  # noqa: BLE001
            return None

    @classmethod
    def _json_schema_unique_items_safe_equal(cls, left: Any, right: Any) -> bool:
        try:
            comparison = left == right
        except Exception:  # noqa: BLE001
            return False
        return comparison if type(comparison) is bool else False

    @classmethod
    def _json_schema_unique_items_equal_in_either_direction(
        cls, left: Any, right: Any
    ) -> bool:
        return cls._json_schema_unique_items_equal(left, right) or cls._json_schema_unique_items_equal(right, left)


class AgentPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: AgentPayloadSchemaVersion
    claims: Annotated[list[ClaimProposal], Field(max_length=256)]
    intent_proposals: Annotated[list[IntentProposal], Field(max_length=256)]
    limitations: Annotated[list[Limitation], Field(max_length=128)]
    reason_decision: ReasonDecisionPayload | None = None


class AgentPayloadSchemaVersion(RootModel[Literal['wuji.agent-payload.v2']]):
    root: Literal['wuji.agent-payload.v2']


class AgentRunRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identity: RunIdentity
    process_state: RunProcessState
    result_state: RunResultState
    model_mode: ModelMode
    created_at: AwareDatetime
    exited_at: AwareDatetime | None = None
    session_manifest: SessionManifest | None = None


class AllowedAction(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=128, min_length=1)]


class AllowedTargetKind(StrEnum):
    workspace_read = 'workspace_read'
    http_target = 'http_target'


class ApiSchemaVersion(RootModel[Literal['wuji.api.v2']]):
    root: Literal['wuji.api.v2']


class ApplicabilityState(StrEnum):
    current = 'current'
    stale = 'stale'
    disputed = 'disputed'
    retracted = 'retracted'


class ApprovalDecision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: ApiSchemaVersion
    decision: ApprovalDecisionValue
    expected_version: RevisionString
    reason: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class ApprovalDecisionValue(StrEnum):
    approve = 'approve'
    reject = 'reject'


class ApprovalRef(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class ArchiveView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    archive_id: Annotated[StrictStr, Field(min_length=1)]
    source_version: Annotated[StrictStr, Field(min_length=1)]
    imported_at: AwareDatetime
    records: list[RecordView]
    executable: Literal[False]


class ArtifactRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_ref: BlobRef
    state: ArtifactState
    media_type: Annotated[StrictStr, Field(min_length=1)]
    size_bytes: RevisionString
    created_at: AwareDatetime


class ArtifactState(StrEnum):
    staged = 'staged'
    sealed = 'sealed'
    tombstoned = 'tombstoned'


class AssertionRole(StrEnum):
    candidate_fact = 'candidate_fact'
    explanation = 'explanation'
    hypothesis = 'hypothesis'


class AssessmentCommand(_JsonSchemaRuntimeValidationBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    __json_schema_unique_items__: ClassVar[tuple[tuple[object, ...], ...]] = (
        (('supersedes_assessment_ids',),),
    )

    supersedes_assessment_ids: Annotated[
        list[SupersedesAssessmentId] | None,
        Field(max_length=128, validate_default=True),
    ] = []
    supersedes_reason: SupersedesReason | None = None
    schema_version: ApiSchemaVersion
    expected_version: RevisionString
    assessment: FactAssessment


class AssessmentId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class AssessmentMethod(StrEnum):
    deterministic = 'deterministic'
    reproduced_check = 'reproduced_check'
    human_attestation = 'human_attestation'
    model_review = 'model_review'


class AssessmentReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assessment_id: Annotated[StrictStr, Field(min_length=1)]
    revision: RevisionString
    status: ComponentReceiptStatus
    claim_ref: KnowledgeRef
    request_id: Annotated[StrictStr, Field(min_length=1)]
    code: ErrorCode2 | None = None


class AssignmentSchemaVersion(RootModel[Literal['wuji.assignment.v2']]):
    root: Literal['wuji.assignment.v2']


class AuthorizationScopeEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    host: Annotated[StrictStr, Field(max_length=253, min_length=1)]
    protocol: Protocol
    port: Annotated[StrictInt, Field(ge=1, le=65535)]


class BillingState(StrEnum):
    pending = 'pending'
    reported = 'reported'
    unknown = 'unknown'


class BirthId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=1024, min_length=1)]


class BlobRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    version: RevisionString
    sha256: Sha256Digest


class CaptureCompleteness(StrEnum):
    complete = 'complete'
    partial = 'partial'
    unknown = 'unknown'


class CaptureEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: CaptureSchemaVersion
    capture_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    identity: RunIdentity
    tool_call_id: Annotated[StrictStr, Field(max_length=1024, min_length=1)]
    tool_attempt_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    artifact_refs: Annotated[list[BlobRef], Field(max_length=256, min_length=1)]
    capture_layer: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    observed_at: AwareDatetime
    received_at: AwareDatetime
    evidence_origin: EvidenceOrigin
    conditions: Annotated[list[Condition], Field(max_length=128)]
    completeness: CaptureCompleteness


class CaptureSchemaVersion(RootModel[Literal['wuji.capture.v2']]):
    root: Literal['wuji.capture.v2']


class ChatCompletionChoice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    index: Annotated[StrictInt, Field(ge=0, le=1000000)]
    message: ChatMessage
    finish_reason: FinishReason | None


class ChatCompletionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    model: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    messages: Annotated[list[ChatMessage], Field(max_length=4096, min_length=1)]
    tools: Annotated[list[ChatToolDefinition] | None, Field(max_length=256)] = None
    tool_choice: ToolChoice | ToolChoice1 | None = None
    stream: StrictBool
    parallel_tool_calls: StrictBool | None = None
    stream_options: StreamOptions | None = None
    max_tokens: Annotated[StrictInt | None, Field(ge=1, le=1048576)] = None
    max_completion_tokens: Annotated[StrictInt | None, Field(ge=1, le=1048576)] = None
    temperature: Annotated[StrictFloat | None, Field(ge=0.0, le=2.0)] = None


class ChatCompletionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[StrictStr, Field(min_length=1)]
    object: Literal['chat.completion']
    created: Annotated[StrictInt, Field(ge=0, le=9223372036854775807)]
    model: Annotated[StrictStr, Field(min_length=1)]
    choices: list[ChatCompletionChoice]
    usage: TokenUsage


class ChatMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: ChatRole
    content: Content | None = None
    name: Name | None = None
    tool_call_id: ToolCallId | None = None
    tool_calls: Annotated[list[ChatToolCall] | None, Field(max_length=256)] = None


class ChatRole(StrEnum):
    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class ChatToolCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[StrictStr, Field(max_length=1024, min_length=1)]
    type: Literal['function']
    function: ChatToolCallFunction


class ChatToolCallFunction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    arguments: Annotated[StrictStr, Field(max_length=1048576)]


class ChatToolDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['function']
    function: Function


class ClaimAssessmentView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    policy_version: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    grounding_state: GroundingState
    evidence_state: EvidenceState
    applicability_state: ApplicabilityState
    eligible: StrictBool
    assessment_ids: Annotated[list[AssessmentId], Field(max_length=1024)]
    conditions: Annotated[list[Condition3], Field(max_length=1024)]
    limitations: Annotated[list[Limitation3], Field(max_length=1024)]


class ClaimKind(StrEnum):
    observation_summary = 'observation-summary'
    hypothesis = 'hypothesis'
    derived_conclusion = 'derived-conclusion'


class ClaimProposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    revises: KnowledgeRef | None = None
    client_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    kind: ClaimKind
    assertion_role: AssertionRole
    text: Annotated[StrictStr, Field(max_length=32768, min_length=1)]
    structured_assertion: dict[str, Any] | None = None
    basis_refs: Annotated[list[ProposalReference], Field(max_length=256)]
    limitations: Annotated[list[Limitation], Field(max_length=128)]


class ClaimRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claim_id: Annotated[StrictStr, Field(min_length=1)]
    revision: RevisionString
    task_id: Annotated[StrictStr, Field(min_length=1)]
    kind: ClaimKind
    assertion_role: AssertionRole
    text: Annotated[StrictStr, Field(max_length=32768, min_length=1)]
    structured_assertion: dict[str, Any] | None = None
    basis_refs: list[KnowledgeRef]
    limitations: list[Limitation2]
    producer_kind: ProducerKind
    producer_ref: Annotated[StrictStr, Field(min_length=1)]
    created_at: AwareDatetime
    supersedes: KnowledgeRef | None = None


class ClaimWork(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: ApiSchemaVersion
    operation_id: Annotated[StrictStr, Field(min_length=1)]
    leader_epoch: RevisionString
    receiver_id: Annotated[StrictStr, Field(min_length=1)]
    capacity_key: Annotated[StrictStr, Field(min_length=1)]


class CloseTrigger(StrEnum):
    goal_satisfied = 'goal_satisfied'
    user_cancel = 'user_cancel'
    budget_exhausted = 'budget_exhausted'
    time_limit = 'time_limit'
    no_progress = 'no_progress'
    system_failure = 'system_failure'
    operator_finish = 'operator_finish'


class CommandDisposition(StrEnum):
    accepted = 'accepted'
    rejected = 'rejected'
    already_recorded = 'already_recorded'


class CommandReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command_id: Annotated[StrictStr, Field(min_length=1)]
    disposition: CommandDisposition
    resource_ref: CommandResourceRef
    resource_version: RevisionString
    request_id: Annotated[StrictStr, Field(min_length=1)]
    code: ErrorCode2 | None = None


class CommandResourceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entity_type: CommandResourceType
    id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    revision: RevisionString


class CommandResourceType(StrEnum):
    task = 'task'
    work_item = 'work_item'
    approval = 'approval'


class Completeness(StrEnum):
    complete = 'complete'
    partial = 'partial'
    unknown = 'unknown'


class ComponentReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: ComponentReceiptStatus
    local_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    request_id: Annotated[StrictStr, Field(min_length=1)]
    canonical_ref: KnowledgeRef | None = None
    code: ErrorCode2 | None = None


class ComponentReceiptStatus(StrEnum):
    accepted_shared = 'accepted_shared'
    accepted_for_check = 'accepted_for_check'
    rejected = 'rejected'


class Condition(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class Condition2(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(min_length=1)]


class Condition3(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class Content(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=1048576)]


class Continuation(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=4096, min_length=1)]


class ControlAction(StrEnum):
    stop_after_current = 'stop_after_current'
    stop = 'stop'
    query = 'query'


class ControlOperationId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class ControlReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    operation_id: Annotated[StrictStr, Field(min_length=1)]
    identity: RunIdentity
    status: ControlStatus
    process_state: RunProcessState
    request_id: Annotated[StrictStr, Field(min_length=1)]


class ControlStatus(StrEnum):
    accepted = 'accepted'
    rejected = 'rejected'
    already_recorded = 'already_recorded'


class Cursor(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=4096, min_length=1)]


class DecimalString(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern='^(0|[1-9][0-9]*)(\\.[0-9]+)?$')]


class DeliveryId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class DependencyCondition(StrEnum):
    settled = 'settled'
    accepted_result = 'accepted_result'
    criterion_satisfied = 'criterion_satisfied'


class DispatchReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    operation_id: Annotated[StrictStr, Field(min_length=1)]
    status: DispatchStatus
    assignment: WorkerAssignment | None = None
    request_id: Annotated[StrictStr, Field(min_length=1)]
    code: ErrorCode2 | None = None


class DispatchStatus(StrEnum):
    prepared = 'prepared'
    duplicate = 'duplicate'
    rejected = 'rejected'


class ErrorCode(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class ErrorCode2(StrEnum):
    UNAUTHENTICATED = 'UNAUTHENTICATED'
    FORBIDDEN_COLLECTOR = 'FORBIDDEN_COLLECTOR'
    FORBIDDEN_ASSESSOR = 'FORBIDDEN_ASSESSOR'
    NOT_FOUND_OR_FORBIDDEN = 'NOT_FOUND_OR_FORBIDDEN'
    STALE_VERSION = 'STALE_VERSION'
    STALE_EXECUTION = 'STALE_EXECUTION'
    STALE_INPUT = 'STALE_INPUT'
    SESSION_FRONTIER_MISMATCH = 'SESSION_FRONTIER_MISMATCH'
    INPUT_DIGEST_CONFLICT = 'INPUT_DIGEST_CONFLICT'
    OPERATION_UNKNOWN = 'OPERATION_UNKNOWN'
    SNAPSHOT_EXPIRED = 'SNAPSHOT_EXPIRED'
    VIEW_EXPIRED = 'VIEW_EXPIRED'
    HISTORY_UNAVAILABLE = 'HISTORY_UNAVAILABLE'
    INVALID_REFERENCE = 'INVALID_REFERENCE'
    INVALID_WAIT = 'INVALID_WAIT'
    INVALID_SCHEMA = 'INVALID_SCHEMA'
    INVALID_SCHEMA_VERSION = 'INVALID_SCHEMA_VERSION'
    LIMIT_BLOCKED = 'LIMIT_BLOCKED'
    CAPABILITY_UNAVAILABLE = 'CAPABILITY_UNAVAILABLE'


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: ErrorCode2
    message: Annotated[StrictStr, Field(max_length=8192, min_length=1)]
    request_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    retryable: StrictBool
    details: dict[str, Any]


class EvidenceOrigin(StrEnum):
    live_capture = 'live_capture'
    fixture_capture = 'fixture_capture'
    imported_unverified = 'imported_unverified'


class EvidenceReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    observation_ref: KnowledgeRef | None
    capture_id: Annotated[StrictStr, Field(min_length=1)]
    status: EvidenceReceiptStatus
    artifact_refs: list[BlobRef]
    request_id: Annotated[StrictStr, Field(min_length=1)]
    code: ErrorCode2 | None = None


class EvidenceReceiptStatus(StrEnum):
    pending = 'pending'
    accepted = 'accepted'
    rejected = 'rejected'
    historical_only = 'historical_only'


class EvidenceRequirement(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class EvidenceState(StrEnum):
    unassessed = 'unassessed'
    supported = 'supported'
    contradicted = 'contradicted'
    inconclusive = 'inconclusive'


class ExecutionLimits(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    max_work_items: Annotated[StrictInt, Field(ge=1, le=1000000)]
    max_reason_runs: Annotated[StrictInt, Field(ge=0, le=1000000)]
    max_model_requests: Annotated[StrictInt, Field(ge=0, le=1000000)]
    max_tool_calls: Annotated[StrictInt, Field(ge=0, le=1000000)]
    max_single_output_bytes: Annotated[StrictInt, Field(ge=1, le=1073741824)]
    max_total_output_bytes: Annotated[StrictInt, Field(ge=1, le=1099511627776)]
    max_elapsed_seconds: Annotated[StrictInt, Field(ge=1, le=31536000)]
    max_attempts_per_work: Annotated[StrictInt, Field(ge=1, le=1000)]
    repair_attempts: Annotated[StrictInt, Field(ge=0, le=1000)]


class ExecutorAttemptId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(pattern='^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'),
    ]


class ExecutorCancelRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    permit: ExecutorPermitDocument
    permit_digest: Sha256Digest
    reason: Annotated[StrictStr, Field(max_length=4096, min_length=1)]


class ExecutorDispatchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    permit: ExecutorPermitDocument
    permit_digest: Sha256Digest


class ExecutorPermitCheckRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identity: RunIdentity
    tool_attempt_id: ExecutorAttemptId
    execution_token: Annotated[StrictStr, Field(max_length=16384, min_length=1)]
    permit_digest: Sha256Digest
    purpose: ExecutorPermitPurpose


class ExecutorPermitCheckResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool_attempt_id: ExecutorAttemptId
    permit_digest: Sha256Digest
    purpose: ExecutorPermitPurpose


class ExecutorPermitDocument(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool_call_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    tool_attempt_id: ExecutorAttemptId
    identity: RunIdentity
    executor_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    tool_definition_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    arguments: dict[str, Any]
    arguments_digest: Sha256Digest
    resource_keys: Annotated[list[ResourceKey], Field(max_length=1024)]
    expires_at: AwareDatetime
    execution_token: Annotated[StrictStr, Field(max_length=16384, min_length=1)]
    subject: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    token_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    roles: Annotated[list[Role], Field(max_length=64, min_length=1)]
    runtime: dict[str, Any]


class ExecutorPermitPurpose(StrEnum):
    check_execution = 'check_execution'
    validate_receipt = 'validate_receipt'


class ExecutorQueryRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    permit: ExecutorPermitDocument
    permit_digest: Sha256Digest


class ExecutorReceiptResponse1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool_attempt_id: ExecutorAttemptId
    receiver_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    receipt_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    status: Status
    started_at: AwareDatetime | None
    exited_at: AwareDatetime | None
    source_receipt: dict[str, Any]
    output_base64: OutputBase64 | None
    output_bytes: OutputBytes | None
    output_sha256: Sha256Digest | None
    media_type: MediaType | None
    completeness: Completeness
    error_code: ErrorCode | None
    permit_digest: Sha256Digest


class ExecutorReceiptResponse2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool_attempt_id: ExecutorAttemptId
    receiver_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    receipt_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    status: Status
    started_at: AwareDatetime | None
    exited_at: AwareDatetime | None
    source_receipt: dict[str, Any]
    output_base64: OutputBase64 | None
    output_bytes: OutputBytes | None
    output_sha256: Sha256Digest | None
    media_type: MediaType | None
    completeness: Completeness
    error_code: ErrorCode | None
    permit_digest: Sha256Digest


from pydantic import model_validator as _executor_model_validator


class ExecutorReceiptResponse(
    RootModel[ExecutorReceiptResponse1 | ExecutorReceiptResponse2]
):
    root: Annotated[
        ExecutorReceiptResponse1 | ExecutorReceiptResponse2,
        Field(
            description='Output fields are all null or all present. Empty bytes use an empty base64 string, count "0" and SHA256 of empty bytes. Consumers verify canonical base64, exact decoded byte count, digest and deployment limit before constructing the domain receipt. An unknown receipt is not exit.'
        ),
    ]

    @_executor_model_validator(mode="after")
    def _validate_source_one_of(self):
        branches = ((('output_base64', 'null'), ('output_bytes', 'null'), ('output_sha256', 'null')), (('output_base64', 'string'), ('output_bytes', 'string'), ('output_sha256', 'string')))
        value = self.root
        matches = 0
        for branch in branches:
            valid = True
            for name, expected_type in branch:
                field = getattr(value, name)
                field = getattr(field, "root", field)
                valid = valid and (field is None if expected_type == "null" else isinstance(field, str))
            matches += valid
        if matches != 1:
            raise ValueError("ExecutorReceiptResponse must match exactly one source oneOf branch")
        return self


class FactAssessment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assessment_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    claim_ref: KnowledgeRef
    input_refs: Annotated[list[KnowledgeRef], Field(max_length=256, min_length=1)]
    grounding_state: GroundingState
    evidence_state: EvidenceState
    applicability_state: ApplicabilityState
    method_kind: AssessmentMethod
    method_version: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    reviewer_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    conditions: Annotated[list[Condition], Field(max_length=128)]
    reason: Annotated[StrictStr, Field(max_length=32768, min_length=1)]


class FinishReason(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=128, min_length=1)]


class Function(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    description: Annotated[StrictStr, Field(max_length=8192)]
    parameters: dict[str, Any]


class Function1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class GatewaySpendRef(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class GatewayUsageRef(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class GenericRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ref: KnowledgeRef
    title: Annotated[StrictStr, Field(min_length=1)]
    summary: Annotated[StrictStr, Field(min_length=1)]
    created_at: AwareDatetime
    test_result: TestResult | None = None
    report_delivery_state: ReportDeliveryState | None = None


class GoalContractInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Annotated[StrictStr, Field(max_length=65536, min_length=1)]
    criteria: Annotated[list[GoalCriterionInput], Field(max_length=256, min_length=1)]


class GoalCriterionInput(_JsonSchemaRuntimeValidationBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    __json_schema_unique_items__: ClassVar[tuple[tuple[object, ...], ...]] = (
        (('allowed_methods',),),
    )

    criterion_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    object: Annotated[StrictStr, Field(max_length=8192, min_length=1)]
    condition: Annotated[StrictStr, Field(max_length=8192, min_length=1)]
    evidence_requirements: Annotated[
        list[EvidenceRequirement], Field(max_length=128, min_length=1)
    ]
    allowed_methods: Annotated[list[AssessmentMethod], Field(min_length=1)]
    responsible_party: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    required: StrictBool


class GoalCriterionRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    criterion_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    revision: RevisionString


class GoalRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    goal_id: Annotated[StrictStr, Field(min_length=1)]
    revision: RevisionString
    text: Annotated[StrictStr, Field(min_length=1)]
    status: GoalStatus
    criterion_refs: Annotated[list[KnowledgeRef], Field(min_length=1)]


class GoalStatus(StrEnum):
    met = 'met'
    not_met = 'not_met'
    unknown = 'unknown'
    not_applicable = 'not_applicable'


class GroundingState(StrEnum):
    unchecked = 'unchecked'
    linked = 'linked'
    content_checked = 'content_checked'
    invalid = 'invalid'


class GroupingState(StrEnum):
    known = 'known'
    grouping_unknown = 'grouping_unknown'


class IntentAcceptance(StrEnum):
    proposed = 'proposed'
    admitted = 'admitted'
    rejected = 'rejected'
    superseded = 'superseded'


class IntentProposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    question: Annotated[StrictStr, Field(max_length=32768, min_length=1)]
    basis_refs: Annotated[list[ProposalReference], Field(max_length=256)]
    expected_output: Annotated[StrictStr, Field(max_length=32768, min_length=1)]


class IntentRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    intent_id: Annotated[StrictStr, Field(min_length=1)]
    revision: RevisionString
    task_id: Annotated[StrictStr, Field(min_length=1)]
    question: Annotated[StrictStr, Field(min_length=1)]
    basis_refs: list[KnowledgeRef]
    expected_output: Annotated[StrictStr, Field(min_length=1)]
    acceptance_state: IntentAcceptance
    created_at: AwareDatetime


class KnowledgeRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entity_type: NodeEntityType
    id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    revision: RevisionString


class Label(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class LayoutAnchor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entity_type: NodeEntityType
    id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    revision: RevisionString | None = None


class LayoutEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    anchor: LayoutAnchor
    x: Annotated[StrictFloat, Field(ge=-10000000.0, le=10000000.0)]
    y: Annotated[StrictFloat, Field(ge=-10000000.0, le=10000000.0)]
    pinned: StrictBool


class LayoutPatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: ApiSchemaVersion
    selection_mode: ViewSelectionMode
    entries: Annotated[list[LayoutEntry], Field(max_length=1000)]
    viewport: LayoutViewport


class LayoutPreference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: ApiSchemaVersion
    view_name: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    layout_revision: RevisionString
    selection_mode: ViewSelectionMode
    entries: Annotated[list[LayoutEntry], Field(max_length=1000)]
    viewport: LayoutViewport


class LayoutReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    view_name: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    layout_revision: RevisionString
    request_id: Annotated[StrictStr, Field(min_length=1)]


class LayoutViewport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: Annotated[StrictFloat, Field(ge=-10000000.0, le=10000000.0)]
    y: Annotated[StrictFloat, Field(ge=-10000000.0, le=10000000.0)]
    zoom: Annotated[StrictFloat, Field(ge=0.2, le=2.0)]


class Limitation(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class Limitation2(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(min_length=1)]


class Limitation3(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class LocalState(StrEnum):
    inflight = 'inflight'
    ended = 'ended'
    unknown = 'unknown'


class LogicalRequestId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class MediaType(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class MemoryMode(StrEnum):
    disabled = 'disabled'
    pinned_context = 'pinned_context'


class ModelAttemptReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    model_attempt_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    input_digest: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    logical_request_id: LogicalRequestId | None
    grouping_state: GroupingState
    admission_state: Literal['admitted']
    send_state: SendState
    response_state: ResponseState
    billing_state: BillingState
    local_state: LocalState
    inflight: StrictBool
    upstream_status: UpstreamStatus | None
    response_available: StrictBool
    gateway_usage_ref: GatewayUsageRef | None
    gateway_spend_ref: GatewaySpendRef | None
    received_bytes: RevisionString
    retained_bytes: RevisionString
    forwarded_bytes: RevisionString
    output_bytes: RevisionString


class ModelMode(StrEnum):
    synthetic = 'synthetic'
    real = 'real'
    unknown = 'unknown'


class MoneyBudget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    amount: DecimalString
    currency: Literal['USD']


class Name(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class NodeEntityType(StrEnum):
    origin = 'origin'
    goal = 'goal'
    observation = 'observation'
    artifact = 'artifact'
    claim = 'claim'
    intent = 'intent'
    work_item = 'work_item'
    agent_run = 'agent_run'
    verification = 'verification'
    completion_review = 'completion_review'
    finding = 'finding'
    report = 'report'


class ObservationId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class ObservationRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    observation_id: Annotated[StrictStr, Field(min_length=1)]
    revision: RevisionString
    task_id: Annotated[StrictStr, Field(min_length=1)]
    capture_id: Annotated[StrictStr, Field(min_length=1)]
    tool_attempt_id: Annotated[StrictStr, Field(min_length=1)]
    collector_ref: Annotated[StrictStr, Field(min_length=1)]
    artifact_refs: Annotated[list[BlobRef], Field(max_length=256, min_length=1)]
    capture_layer: Annotated[StrictStr, Field(min_length=1)]
    observed_at: AwareDatetime
    received_at: AwareDatetime
    environment_ref: Annotated[StrictStr, Field(min_length=1)]
    conditions: list[Condition2]
    completeness: CaptureCompleteness
    evidence_origin: EvidenceOrigin


class OpaqueCursor(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=4096, min_length=1)]


class OutputBase64(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(json_schema_extra={'contentEncoding': 'base64'}, max_length=89478488),
    ]


class OutputBytes(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=20, pattern='^(0|[1-9][0-9]*)$')]


class PendingOperationRef(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=1024, min_length=1)]


class ProcessIdentity(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(min_length=1)]


class ProducerKind(StrEnum):
    agent = 'agent'
    human = 'human'
    extractor = 'extractor'
    import_ = 'import'


class ProfileRef(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class ProposalLocalRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class ProposalReference(RootModel[KnowledgeRef | ProposalLocalRef]):
    root: KnowledgeRef | ProposalLocalRef


class Protocol(StrEnum):
    http = 'http'
    https = 'https'


class ReasonDecision(StrEnum):
    propose_intents = 'propose_intents'
    wait = 'wait'
    propose_completion = 'propose_completion'
    blocked = 'blocked'


class ReasonDecisionPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decision: ReasonDecision
    wait_refs: Annotated[list[WaitRef], Field(max_length=128)]
    reason: Annotated[StrictStr, Field(max_length=32768, min_length=1)]


class ReceiverBridgeGrant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identity: RunIdentity
    assignment_digest: Sha256Digest
    receiver: WorkerReceiver
    action: WorkerBridgeAction
    subject: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    execution_allowed: StrictBool
    valid_until: AwareDatetime


class ReceiverBridgeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment: WorkerAssignment
    assignment_digest: Sha256Digest
    receiver: WorkerReceiver
    action: WorkerBridgeAction
    control_operation_id: ControlOperationId | None


class RecordView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assessment: ClaimAssessmentView | None = None
    ref: KnowledgeRef
    display_kind: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    record: RecordPayload


class RecoveryClass(StrEnum):
    settled_boundary = 'settled_boundary'
    approval_boundary = 'approval_boundary'
    non_resumable = 'non_resumable'


class ReportDeliveryState(StrEnum):
    delivery_pending = 'delivery_pending'
    ready = 'ready'
    incomplete = 'incomplete'
    failed = 'failed'


class ResourceKey(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=4096, min_length=1)]


class ResponseState(StrEnum):
    pending = 'pending'
    complete = 'complete'
    partial = 'partial'
    unknown = 'unknown'


class ResultEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: ResultEnvelopeSchemaVersion
    submission_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    identity: RunIdentity
    snapshot_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    read_set: Annotated[list[KnowledgeRef], Field(max_length=4096)]
    raw_output_ref: BlobRef
    raw_output_digest: Sha256Digest
    payload: Annotated[
        Any,
        Field(
            description='Untrusted JSON value or null; validate AgentPayload only after sealing and receiving raw output.'
        ),
    ]
    producer_version: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class ResultEnvelopeSchemaVersion(RootModel[Literal['wuji.result-envelope.v2']]):
    root: Literal['wuji.result-envelope.v2']


class ResultOutcome(StrEnum):
    complete = 'complete'
    partial = 'partial'
    inconclusive = 'inconclusive'
    not_assessed = 'not_assessed'


class ResultReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    submission_id: Annotated[StrictStr, Field(min_length=1)]
    status: ResultReceiptStatus
    components: list[ComponentReceipt]
    request_id: Annotated[StrictStr, Field(min_length=1)]
    code: ErrorCode2 | None = None


class ResultReceiptStatus(StrEnum):
    received = 'received'
    accepted = 'accepted'
    rejected = 'rejected'
    historical_only = 'historical_only'


class ResumeReason(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class RevisionString(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern='^(0|[1-9][0-9]*)$')]


class Role(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class RunIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tenant_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    task_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    work_item_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    agent_run_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    execution_epoch: RevisionString
    run_epoch: RevisionString
    runtime_attempt: RevisionString
    receiver_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class RunProcessState(StrEnum):
    registered = 'registered'
    starting = 'starting'
    running = 'running'
    stopping = 'stopping'
    exited = 'exited'
    unknown = 'unknown'


class RunResultState(StrEnum):
    none = 'none'
    received = 'received'
    accepted = 'accepted'
    rejected = 'rejected'
    historical_only = 'historical_only'
    incomplete = 'incomplete'


class ScenarioKind(StrEnum):
    ctf = 'ctf'
    web_single = 'web_single'
    comprehensive = 'comprehensive'
    adversary_emulation = 'adversary_emulation'
    code_audit = 'code_audit'


class SdkApprovalId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class SdkContentId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class SendState(StrEnum):
    not_sent = 'not_sent'
    sending = 'sending'
    sent = 'sent'
    unknown = 'unknown'


class SessionManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    work_item_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    checkpoint_revision: RevisionString
    owner_run_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    run_epoch: RevisionString
    history_root: BlobRef
    message_end: RevisionString
    provider_state_ref: BlobRef
    memory_manifest_ref: BlobRef
    pending_operation_refs: Annotated[list[PendingOperationRef], Field(max_length=512)]
    lock_digest: Sha256Digest
    recovery_class: RecoveryClass
    saved_at: AwareDatetime


class SessionManifestRef(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class Sha256Digest(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern='^[a-f0-9]{64}$')]


class SnapshotId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class SnapshotIndex(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[SnapshotSummary]
    opaque_cursor: OpaqueCursor | None


class SnapshotSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    snapshot_id: Annotated[StrictStr, Field(min_length=1)]
    view_id: Annotated[StrictStr, Field(min_length=1)]
    view_revision: RevisionString
    created_at: AwareDatetime
    query_digest: Annotated[StrictStr, Field(min_length=1)]
    projection_version: Annotated[StrictStr, Field(min_length=1)]
    query: ViewQuery | None = None


class StartReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    operation_id: Annotated[StrictStr, Field(min_length=1)]
    identity: RunIdentity
    status: StartStatus
    process_identity: ProcessIdentity | None
    request_id: Annotated[StrictStr, Field(min_length=1)]


class StartStatus(StrEnum):
    prepared = 'prepared'
    running = 'running'
    already_recorded = 'already_recorded'
    rejected = 'rejected'
    unknown = 'unknown'


class State(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=128, min_length=1)]


class Status(StrEnum):
    not_started = 'not_started'
    running = 'running'
    exited = 'exited'
    unknown = 'unknown'


class Status2(StrEnum):
    pending_approval = 'pending_approval'
    admitted = 'admitted'
    dispatched = 'dispatched'
    running = 'running'
    evidence_pending = 'evidence_pending'
    complete = 'complete'
    unknown = 'unknown'
    cancel_requested = 'cancel_requested'
    cancelled = 'cancelled'
    failed = 'failed'


class StreamOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    include_usage: StrictBool


class SupersedesAssessmentId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class SupersedesReason(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class SuspensionCause(StrEnum):
    user_hold = 'user_hold'
    task_pause = 'task_pause'
    completion_epoch = 'completion_epoch'
    scope_revoked = 'scope_revoked'


class TaskCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: ApiSchemaVersion
    command: TaskCommandName
    expected_version: RevisionString
    reason: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class TaskCommandName(StrEnum):
    start = 'start'
    pause = 'pause'
    resume = 'resume'
    cancel = 'cancel'
    finish = 'finish'


class TaskCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: ApiSchemaVersion
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    name: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    scenario: ScenarioKind
    goal: GoalContractInput
    authorization_scope: Annotated[
        list[AuthorizationScopeEntry], Field(max_length=1024, min_length=1)
    ]
    authorization_expires_at: AwareDatetime
    model_profile_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    runtime_profile_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    budget: MoneyBudget


class TaskDesired(StrEnum):
    run = 'run'
    pause = 'pause'
    cancel = 'cancel'
    finish = 'finish'


class TaskObserved(StrEnum):
    ready = 'ready'
    running = 'running'
    quiescing = 'quiescing'
    paused = 'paused'
    reconciling = 'reconciling'
    closed = 'closed'


class TaskView(_JsonSchemaRuntimeValidationBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    __json_schema_unique_items__: ClassVar[tuple[tuple[object, ...], ...]] = (
        (('allowed_actions',),),
    )

    task_id: Annotated[StrictStr, Field(min_length=1)]
    tenant_id: Annotated[StrictStr, Field(min_length=1)]
    project_id: Annotated[StrictStr, Field(min_length=1)]
    version: RevisionString
    name: Annotated[StrictStr, Field(min_length=1)]
    scenario: ScenarioKind
    desired_state: TaskDesired
    observed_state: TaskObserved
    goal_revision: RevisionString
    execution_epoch: RevisionString
    activated_at: AwareDatetime | None = None
    close_trigger: CloseTrigger | None = None
    result_outcome: ResultOutcome | None = None
    allowed_actions: list[TaskCommandName]


class TerminalReason(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(min_length=1)]


class TestResult(StrEnum):
    pass_ = 'pass'
    fail = 'fail'
    not_run = 'not_run'
    blocked = 'blocked'


class TokenUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    prompt_tokens: Annotated[StrictInt, Field(ge=0, le=9223372036854775807)]
    completion_tokens: Annotated[StrictInt, Field(ge=0, le=9223372036854775807)]
    total_tokens: Annotated[StrictInt, Field(ge=0, le=9223372036854775807)]


class ToolAttemptId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class ToolCallId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=1024, min_length=1)]


class ToolCallReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool_call_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    operation_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    tool_attempt_id: ToolAttemptId | None
    status: Status2
    evidence_receipt: EvidenceReceipt | None
    result_ref: BlobRef | None
    reason_code: ErrorCode2 | None


class ToolCallRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    session_lineage: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    message_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    provider_call_id: Annotated[StrictStr, Field(max_length=1024, min_length=1)]
    tool_definition_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    arguments: dict[str, Any]
    sdk_content_id: SdkContentId | None = None
    sdk_approval_id: SdkApprovalId | None = None
    approval_ref: ApprovalRef | None = None


class ToolCancelRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reason: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class ToolChoice(StrEnum):
    none = 'none'
    auto = 'auto'
    required = 'required'


class ToolChoice1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['function']
    function: Function1


class ToolDefinitionRef(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class TopologyEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[StrictStr, Field(max_length=1024, min_length=1)]
    source: Annotated[StrictStr, Field(max_length=1024, min_length=1)]
    target: Annotated[StrictStr, Field(max_length=1024, min_length=1)]
    edge_type: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    label: Label | None = None


class TopologyNode(_JsonSchemaRuntimeValidationBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    __json_schema_unique_items__: ClassVar[tuple[tuple[object, ...], ...]] = (
        (('allowed_actions',),),
    )

    id: Annotated[StrictStr, Field(max_length=1024, min_length=1)]
    ref: KnowledgeRef
    display_kind: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    label: Annotated[StrictStr, Field(max_length=8192, min_length=1)]
    state: State | None = None
    allowed_actions: list[AllowedAction] | None = None


class TopologySnapshot(_JsonSchemaRuntimeValidationBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    __json_schema_unique_items__: ClassVar[tuple[tuple[object, ...], ...]] = (
        (('allowed_actions',),),
    )

    view_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    snapshot_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    view_revision: RevisionString
    query_digest: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    access_scope_digest: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    projection_version: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    nodes: Annotated[list[TopologyNode], Field(max_length=1000)]
    edges: Annotated[list[TopologyEdge], Field(max_length=2000)]
    opaque_cursor: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    truncated: StrictBool
    continuation: Continuation | None
    allowed_actions: list[AllowedAction]


class UpstreamStatus(RootModel[StrictInt]):
    root: Annotated[StrictInt, Field(ge=100, le=599)]


class ViewEventBatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: ViewEventSchemaVersion
    view_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    base_view_revision: RevisionString
    view_revision: RevisionString
    cursor: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    patches: Annotated[list[ViewPatch], Field(max_length=2000, min_length=1)]


class ViewEventSchemaVersion(RootModel[Literal['wuji.view-event.v2']]):
    root: Literal['wuji.view-event.v2']


class ViewMode(StrEnum):
    live = 'live'
    history = 'history'


class ViewPatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    op: ViewPatchOperation
    value: ViewPatchValue


class ViewPatchOperation(StrEnum):
    upsert_node = 'upsert_node'
    remove_node = 'remove_node'
    upsert_edge = 'upsert_edge'
    remove_edge = 'remove_edge'


class ViewQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: ViewMode
    snapshot_id: SnapshotId | None
    cursor: Cursor | None
    node_limit: Annotated[StrictInt, Field(ge=1, le=1000)]
    edge_limit: Annotated[StrictInt, Field(ge=1, le=2000)]


class ViewRemoval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[StrictStr, Field(max_length=1024, min_length=1)]


class ViewPatchValue(RootModel[TopologyNode | TopologyEdge | ViewRemoval]):
    root: TopologyNode | TopologyEdge | ViewRemoval


class ViewReset(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: ViewResetSchemaVersion
    view_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    reason: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    action: ViewResetAction


class ViewResetAction(RootModel[Literal['resnapshot']]):
    root: Literal['resnapshot']


class ViewResetSchemaVersion(RootModel[Literal['wuji.view-reset.v2']]):
    root: Literal['wuji.view-reset.v2']


class ViewSelectionMode(StrEnum):
    explicit_revision = 'explicit_revision'
    follow_latest = 'follow_latest'


class WaitRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ref: ProposalReference
    predicate: Annotated[StrictStr, Field(max_length=1024, min_length=1)]
    predicate_version: RevisionString


class WorkCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: ApiSchemaVersion
    command: WorkCommandName
    expected_version: RevisionString
    reason: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class WorkCommandName(StrEnum):
    hold = 'hold'
    resume = 'resume'
    cancel = 'cancel'


class WorkDependency(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    predecessor_work_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    condition: DependencyCondition
    criterion_ref: GoalCriterionRef | None = None


class WorkDesired(StrEnum):
    run = 'run'
    hold = 'hold'
    cancel = 'cancel'


class WorkItemView(_JsonSchemaRuntimeValidationBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    __json_schema_unique_items__: ClassVar[tuple[tuple[object, ...], ...]] = (
        (('suspension_causes',),),
    )

    work_item_id: Annotated[StrictStr, Field(min_length=1)]
    task_id: Annotated[StrictStr, Field(min_length=1)]
    revision: RevisionString
    kind: WorkKind
    desired_state: WorkDesired
    state: WorkState
    dependencies: list[WorkDependency]
    suspension_causes: list[SuspensionCause]
    result_state: RunResultState
    terminal_reason: TerminalReason | None = None


class RecordPayload(
    RootModel[
        TaskView
        | WorkItemView
        | ClaimRecord
        | ObservationRecord
        | ArtifactRecord
        | IntentRecord
        | AgentRunRecord
        | GoalRecord
        | GenericRecord
    ]
):
    root: TaskView | WorkItemView | ClaimRecord | ObservationRecord | ArtifactRecord | IntentRecord | AgentRunRecord | GoalRecord | GenericRecord


class WorkKind(StrEnum):
    reason = 'reason'
    explore = 'explore'
    report = 'report'


class WorkState(StrEnum):
    ready = 'ready'
    leased = 'leased'
    running = 'running'
    waiting_input = 'waiting_input'
    blocked = 'blocked'
    stopping = 'stopping'
    suspended = 'suspended'
    reconciling = 'reconciling'
    done = 'done'
    failed = 'failed'
    cancelled = 'cancelled'


class WorkerAcknowledgeDeliveryRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment: WorkerAssignment
    delivery_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    payload_digest: Sha256Digest


class WorkerArchiveRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment: WorkerAssignment
    sdk_output_base64: Annotated[StrictStr, Field(max_length=22369624, min_length=1)]
    sdk_digest: Sha256Digest


class WorkerAssignment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: AssignmentSchemaVersion
    operation_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    identity: RunIdentity
    work_kind: WorkKind
    snapshot_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    profile_refs: Annotated[list[ProfileRef], Field(max_length=64, min_length=1)]
    session_manifest_ref: SessionManifestRef | None
    tool_definition_refs: Annotated[list[ToolDefinitionRef], Field(max_length=256)]
    limits: ExecutionLimits
    resume_reason: ResumeReason | None


class WorkerBootstrap(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment: WorkerAssignment
    assignment_digest: Sha256Digest
    receiver: WorkerReceiver
    run_credential: Annotated[StrictStr, Field(max_length=16384, min_length=1)]
    public_key_pem: Annotated[StrictStr, Field(max_length=16384, min_length=1)]
    issuer: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    audience: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    host_origin: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    model_gate_url: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    tool_gate_url: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    wait_timeout_seconds: Annotated[StrictInt, Field(ge=1, le=300)]
    transport_timeout_seconds: Annotated[StrictInt, Field(ge=1, le=60)]
    max_transport_bytes: Annotated[StrictInt, Field(ge=1, le=67108864)]


class WorkerBridgeAction(StrEnum):
    query = 'query'
    start = 'start'
    stop = 'stop'
    stop_after_current = 'stop_after_current'


class WorkerBridgeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment: WorkerAssignment


class WorkerContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    snapshot_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    read_set: Annotated[list[KnowledgeRef], Field(max_length=5000)]
    record_refs: Annotated[list[KnowledgeRef], Field(max_length=5000)]
    text: Annotated[StrictStr, Field(max_length=16777216)]
    input_digest: Sha256Digest


class WorkerControl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: ApiSchemaVersion
    operation_id: Annotated[StrictStr, Field(min_length=1)]
    identity: RunIdentity
    action: ControlAction
    reason: Annotated[StrictStr, Field(max_length=8192, min_length=1)]


class WorkerHarnessCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    todo: StrictBool
    mode: StrictBool
    file_memory: StrictBool
    file_access: StrictBool
    skills: StrictBool
    shell: StrictBool
    web_search: StrictBool
    background_agents: StrictBool
    outer_loop: StrictBool
    auto_approval: StrictBool
    compaction: StrictBool
    restoration: StrictBool
    mcp: StrictBool


class WorkerHarnessProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    revision: RevisionString
    digest: Sha256Digest
    body: WorkerHarnessProfileBody | WorkerSessionHarnessProfileBody


class WorkerHarnessProfileBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    revision: RevisionString
    work_kind: WorkKind
    instructions: Annotated[StrictStr, Field(max_length=32768, min_length=1)]
    tool_definition_refs: Annotated[
        list[ToolDefinitionRef], Field(max_length=256, min_length=1)
    ]
    lock_digest: Sha256Digest
    max_context_records: Annotated[StrictInt, Field(ge=1, le=5000)]
    max_context_bytes: Annotated[StrictInt, Field(ge=1, le=16777216)]
    max_output_tokens: Annotated[StrictInt, Field(ge=1, le=1048576)]
    capabilities: WorkerHarnessCapabilities


class WorkerLoadDeliveryRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment: WorkerAssignment
    delivery_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class WorkerLoadSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment: WorkerAssignment
    manifest_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class WorkerPublishSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment: WorkerAssignment
    manifest: SessionManifest
    expected_revision: RevisionString


class WorkerReceiver(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    receiver_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    runtime_attempt: RevisionString
    environment_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    pod_uid: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class WorkerRegisterInputRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment: WorkerAssignment
    observation: WorkerSessionPayload


class WorkerResolvedContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    context: WorkerContext
    resolved: WorkerResolvedHost | WorkerSessionResolvedHost
    assignment_digest: Sha256Digest


class WorkerResolvedHost(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    profile: WorkerHarnessProfile
    client_model: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    limits: ExecutionLimits
    request_timeout_seconds: Annotated[StrictFloat, Field(gt=0.0, le=300.0)]
    tools: Annotated[list[WorkerToolDefinition], Field(max_length=256, min_length=1)]
    session_lineage: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class WorkerSessionBinary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    slot: WorkerSessionBinarySlot
    key: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    data_base64: Annotated[StrictStr, Field(max_length=67108864)]
    data_sha256: Sha256Digest
    size_bytes: Annotated[StrictInt, Field(ge=0, le=67108864)]


class WorkerSessionBinarySlot(StrEnum):
    boundary_object_data = 'boundary_object_data'
    published_object_bytes = 'published_object_bytes'
    resolved_memory_file = 'resolved_memory_file'


class WorkerSessionHarnessCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    todo: StrictBool
    mode: StrictBool
    file_memory: StrictBool
    file_access: StrictBool
    skills: StrictBool
    shell: StrictBool
    web_search: StrictBool
    background_agents: StrictBool
    outer_loop: StrictBool
    auto_approval: StrictBool
    compaction: StrictBool
    restoration: StrictBool
    mcp: StrictBool
    native_approval: StrictBool
    versioned_memory: StrictBool


class WorkerSessionHarnessProfileBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    revision: RevisionString
    work_kind: WorkKind
    instructions: Annotated[StrictStr, Field(max_length=32768, min_length=1)]
    tool_definition_refs: Annotated[
        list[ToolDefinitionRef], Field(max_length=256, min_length=1)
    ]
    lock_digest: Sha256Digest
    max_context_records: Annotated[StrictInt, Field(ge=1, le=5000)]
    max_context_bytes: Annotated[StrictInt, Field(ge=1, le=16777216)]
    max_output_tokens: Annotated[StrictInt, Field(ge=1, le=1048576)]
    capabilities: WorkerSessionHarnessCapabilities
    schema_version: Literal['wuji.harness.session.v1']
    history_source_id: Annotated[StrictStr, Field(pattern='^[a-z][a-z0-9_]{0,63}$')]
    memory_mode: MemoryMode
    memory_source_id: Annotated[StrictStr, Field(pattern='^[a-z][a-z0-9_]{0,63}$')]
    session_limits: WorkerSessionLimits
    max_context_window_tokens: Annotated[StrictInt, Field(ge=1, le=1073741824)]
    compaction_enabled: StrictBool
    memory_inputs: Annotated[
        list[WorkerSessionMemoryInput] | None,
        Field(
            description='Optional fixed memory inputs, bounded by session_limits.max_objects. Absence preserves the original Profile document; content bytes use the existing resolved memory_files field.'
        ),
    ] = None


class WorkerSessionLimits(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    max_objects: Annotated[StrictInt, Field(ge=1, le=10000)]
    max_reference_depth: Annotated[StrictInt, Field(ge=1, le=64)]
    max_object_bytes: Annotated[StrictInt, Field(ge=1, le=67108864)]
    max_total_bytes: Annotated[StrictInt, Field(ge=1, le=67108864)]
    max_messages: Annotated[StrictInt, Field(ge=1, le=100000)]
    max_pending_approvals: Annotated[StrictInt, Field(ge=1, le=512)]


class WorkerSessionMemoryInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: Annotated[
        StrictStr,
        Field(
            description='Relative logical memory path; domain validation additionally limits UTF-8 bytes and rejects traversal, control characters and duplicate paths.',
            max_length=1024,
            min_length=1,
        ),
    ]
    ref: KnowledgeRef


class WorkerSessionPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: WorkerSessionPayloadVersion
    payload: dict[str, Any]
    payload_sha256: Sha256Digest
    payload_size_bytes: Annotated[StrictInt, Field(ge=2, le=67108864)]
    binaries: Annotated[list[WorkerSessionBinary], Field(max_length=10000)]


class WorkerSessionPayloadVersion(StrEnum):
    wuji_worker_session_boundary_v1 = 'wuji.worker.session.boundary.v1'
    wuji_worker_session_staged_v1 = 'wuji.worker.session.staged.v1'
    wuji_worker_session_receipt_v1 = 'wuji.worker.session.receipt.v1'
    wuji_worker_session_published_v1 = 'wuji.worker.session.published.v1'
    wuji_worker_session_approval_observation_v1 = 'wuji.worker.session.approval-observation.v1'
    wuji_worker_session_input_receipt_v1 = 'wuji.worker.session.input-receipt.v1'
    wuji_worker_session_human_input_v1 = 'wuji.worker.session.human-input.v1'
    wuji_worker_session_delivery_receipt_v1 = 'wuji.worker.session.delivery-receipt.v1'
    wuji_worker_session_compatibility_v1 = 'wuji.worker.session.compatibility.v1'


class WorkerSessionResolvedHost(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    profile: WorkerHarnessProfile
    client_model: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    limits: ExecutionLimits
    request_timeout_seconds: Annotated[StrictFloat, Field(gt=0.0, le=300.0)]
    tools: Annotated[list[WorkerToolDefinition], Field(max_length=256, min_length=1)]
    session_lineage: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    session_compatibility: WorkerSessionPayload
    session_limits: WorkerSessionLimits
    delivery_id: DeliveryId | None
    memory_files: Annotated[list[WorkerSessionBinary], Field(max_length=10000)]


class WorkerStageSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment: WorkerAssignment
    boundary: WorkerSessionPayload


class WorkerStartPermission(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: WorkerStartStatus
    identity: RunIdentity
    start_operation_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    assignment_digest: Sha256Digest
    receiver: WorkerReceiver
    birth_id: BirthId | None
    observation_id: ObservationId | None
    source_digest: Sha256Digest | None
    valid_until: AwareDatetime


class WorkerStartStatus(StrEnum):
    wait = 'wait'
    ready = 'ready'
    revoked = 'revoked'


class WorkerSubmitRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment: WorkerAssignment
    context: WorkerContext
    raw_output_base64: Annotated[StrictStr, Field(max_length=22369624, min_length=1)]
    sdk_output_base64: Annotated[StrictStr, Field(max_length=22369624, min_length=1)]
    raw_digest: Sha256Digest
    sdk_digest: Sha256Digest
    tool_receipts: Annotated[list[ToolCallReceipt], Field(max_length=10000)]


class WorkerToolDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    revision: RevisionString
    published_at: AwareDatetime
    name: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    input_schema: dict[str, Any]
    executor_ref: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    approval_required: StrictBool
    allowed_target_kinds: Annotated[
        list[AllowedTargetKind], Field(max_length=2, min_length=1)
    ]
