"""Authorized topology, layout, history, and record view contracts."""

from wuji_core.contracts.generated import (
    ArchiveView,
    LayoutAnchor,
    LayoutEntry,
    LayoutPatch,
    LayoutReceipt,
    RecordView,
    ReportDeliveryState,
    SnapshotIndex,
    SnapshotSummary,
    TopologyEdge,
    TopologyNode,
    TopologySnapshot,
    ViewEventBatch,
    ViewMode,
    ViewPatch,
    ViewPatchOperation,
    ViewReset,
    ViewResetAction,
    ViewQuery,
    ViewSelectionMode,
)

__all__ = [
    "ArchiveView",
    "LayoutAnchor",
    "LayoutEntry",
    "LayoutPatch",
    "LayoutReceipt",
    "RecordView",
    "ReportDeliveryState",
    "SnapshotIndex",
    "SnapshotSummary",
    "TopologyEdge",
    "TopologyNode",
    "TopologySnapshot",
    "ViewEventBatch",
    "ViewMode",
    "ViewPatch",
    "ViewPatchOperation",
    "ViewReset",
    "ViewResetAction",
    "ViewQuery",
    "ViewSelectionMode",
]
