HTTP/1.1 200 OK
date: Thu, 17 Sep 2026 04:44:20 GMT
server: uvicorn
cache-control: no-store
content-length: 817
content-type: application/json
x-request-id: 0bc64715-487d-431f-86c7-b073fc1496b7

[{"delivery_id":"delivery:929b5ad51414c81558cf026b3969adc5","report_id":"report:73a83e16-5f3e-4f02-b509-f59df7a97962","profile_id":"offline-document-v1","mode":"offline","state":"ready","missing_required":0,"error_code":null,"created_at":"2026-09-17T04:12:38.026573Z"},{"delivery_id":"delivery:8b96ebcf68614db4ab47955676543b25","report_id":"report:73a83e16-5f3e-4f02-b509-f59df7a97962","profile_id":"screenshot-bundle-v1","mode":"offline","state":"incomplete","missing_required":1,"error_code":null,"created_at":"2026-09-17T04:12:38.105933Z"},{"delivery_id":"delivery:21563ff39ec7ab74940d15fcbecf91b1","report_id":"report:73a83e16-5f3e-4f02-b509-f59df7a97962","profile_id":"screenshot-bundle-v1","mode":"offline","state":"incomplete","missing_required":1,"error_code":null,"created_at":"2026-09-17T04:19:35.557696Z"}]