HTTP/1.1 422 Unprocessable Content
date: Thu, 17 Sep 2026 04:44:20 GMT
server: uvicorn
content-length: 156
content-type: application/json
cache-control: no-store
x-request-id: 83f84f4b-3bf0-468c-a762-0f598256489e

{"code":"INVALID_SCHEMA","message":"The request could not be completed.","request_id":"83f84f4b-3bf0-468c-a762-0f598256489e","retryable":false,"details":{}}