HTTP/1.1 500 Internal Server Error
date: Thu, 17 Sep 2026 04:12:38 GMT
server: uvicorn
content-length: 21
content-type: text/plain; charset=utf-8
x-request-id: 4c7504d2-f4d8-4ac5-86e5-98ce800f6a47

Internal Server Error