HTTP/1.1 409 Conflict
date: Thu, 17 Sep 2026 04:44:20 GMT
server: uvicorn
content-length: 168
content-type: application/json
cache-control: no-store
x-request-id: acd67568-42d8-47ca-a491-3ecac16e2df9

{"code":"DELIVERY_EXCHANGE_REQUIRED","message":"The request could not be completed.","request_id":"acd67568-42d8-47ca-a491-3ecac16e2df9","retryable":false,"details":{}}