HTTP/1.1 422 Unprocessable Content
date: Thu, 17 Sep 2026 04:44:21 GMT
server: uvicorn
content-length: 287
content-type: application/json
x-request-id: cee0ebc9-a8c4-49aa-b7ee-a23383e3ffa9

{"code":"INVALID_SCHEMA","message":"Request does not satisfy the v2 contract.","request_id":"cee0ebc9-a8c4-49aa-b7ee-a23383e3ffa9","retryable":false,"details":{"errors":[{"type":"missing","loc":["header","<field>"],"msg":"Input does not satisfy the field contract."}],"truncated":false}}