"""Server-owned immutable byte objects; no caller paths, URLs or fetch capability."""

import base64
from datetime import datetime, timezone
import hashlib
import os
from pathlib import Path
from uuid import uuid4

from wuji_core.contracts.envelopes import BlobRef
from wuji_core.http.json_boundary import strict_json_loads
from wuji_core.persistence.uow import AccessContext, DomainError, json_text, row


def require_collector(access: AccessContext):
    if "collector" not in access.principal.roles or "agent" in access.principal.roles:
        raise DomainError("FORBIDDEN_COLLECTOR", 403)


def bound_attempt(tx, attempt_id: str):
    attempt = row(
        tx.connection.execute(
            """SELECT a.*,r.work_item_id,r.receiver_id,r.environment_ref,
        r.execution_epoch,r.run_epoch,r.runtime_attempt,r.execution_allowed,
        b.can_settle AS binding_can_settle FROM vnext.tool_attempt a
        JOIN vnext.agent_run r USING(tenant_id,project_id,task_id,agent_run_id)
        JOIN vnext.collector_binding b USING(tenant_id,project_id,task_id,tool_attempt_id)
        WHERE a.tenant_id=%s AND a.project_id=%s AND a.task_id=%s AND a.tool_attempt_id=%s
        AND b.subject=%s AND NOT b.revoked""",
            (*tx.owner, attempt_id, tx.access.principal.subject),
        )
    )
    if attempt is None:
        raise DomainError("FORBIDDEN_COLLECTOR", 403)
    return attempt


def capture_disposition(tx, attempt):
    if attempt["started_at"] is None:
        raise DomainError("STALE_EXECUTION", 403)
    current = (
        tx.task["execution_allowed"]
        and attempt["execution_allowed"]
        and tx.task["execution_epoch"] == attempt["execution_epoch"]
        and tx.task["runtime_attempt"] == attempt["runtime_attempt"]
    )
    if current and tx.permissions["can_capture"]:
        return "accepted"
    if not current and tx.permissions["can_settle"] and attempt["binding_can_settle"]:
        return "historical_only"
    raise DomainError("STALE_EXECUTION", 403)


class ArtifactStore:
    def __init__(self, uow, root: Path, *, max_bytes=8 * 1024 * 1024):
        self.uow, self.root, self.max_bytes = uow, Path(root).resolve(), max_bytes
        self.root.mkdir(parents=True, exist_ok=True, mode=0o700)

    def _path(self, record):
        # storage_key is a database UUID generated by stage, never an external path.
        return self.root / (str(record["storage_key"]) + ".blob")

    def stage(
        self,
        access,
        task_id,
        tool_attempt_id,
        data: bytes,
        media_type: str,
        *,
        completeness="complete",
        conditions=(),
        provenance="capture",
        access_level=0,
    ):
        require_collector(access)
        if not isinstance(data, bytes) or len(data) > self.max_bytes:
            raise DomainError("LIMIT_BLOCKED", 422)
        if (
            not isinstance(media_type, str)
            or not 1 <= len(media_type) <= 256
            or "\r" in media_type
            or "\n" in media_type
        ):
            raise DomainError("INVALID_SCHEMA", 422)
        if completeness not in {"complete", "partial", "unknown"} or provenance not in {
            "capture",
            "model_output",
            "import",
        }:
            raise DomainError("INVALID_SCHEMA", 422)
        if len(conditions) > 128 or any(
            not isinstance(item, str) or not 1 <= len(item) <= 8192
            for item in conditions
        ):
            raise DomainError("INVALID_SCHEMA", 422)
        if (
            not isinstance(access_level, int)
            or isinstance(access_level, bool)
            or access_level < 0
        ):
            raise DomainError("INVALID_SCHEMA", 422)
        entity_id = str(uuid4())
        storage_key = uuid4()
        digest = hashlib.sha256(data).hexdigest()
        ref = BlobRef.model_validate(
            {"id": entity_id, "version": "1", "sha256": digest}
        )
        # Reserve metadata/lease before writing bytes: a crash leaves a known staged object.
        with self.uow.transaction(access, task_id, capability="evidence") as tx:
            attempt = bound_attempt(tx, tool_attempt_id)
            capture_disposition(tx, attempt)
            origin = (
                "imported_unverified"
                if provenance == "import"
                else attempt["evidence_origin"]
            )
            tx.connection.execute(
                """INSERT INTO vnext.artifact(tenant_id,project_id,task_id,entity_id,revision,
                state,storage_key,sha256,size_bytes,media_type,tool_attempt_id,provenance,evidence_origin,
                capture_layer,environment_ref,completeness,conditions_json,access_level)
                VALUES (%s,%s,%s,%s,1,'staged',%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
                (
                    *tx.owner,
                    entity_id,
                    storage_key,
                    digest,
                    len(data),
                    media_type,
                    tool_attempt_id,
                    provenance,
                    origin,
                    attempt["capture_layer"],
                    attempt["environment_ref"],
                    completeness,
                    json_text(list(conditions)),
                    access_level,
                ),
            )
            tx.connection.execute(
                "INSERT INTO vnext.artifact_lease(tenant_id,project_id,task_id,artifact_id,artifact_revision,lease_owner,expires_at,access_level) VALUES (%s,%s,%s,%s,1,'staging',clock_timestamp()+interval '5 minutes',%s)",
                (*tx.owner, entity_id, access_level),
            )
        with self.uow.transaction(access, task_id, capability="evidence") as tx:
            record = self.record(tx, ref, lock=True)
            if record["state"] != "staged":
                raise DomainError("INVALID_REFERENCE", 422)
            path = self._path(record)
            with path.open("xb") as stream:
                stream.write(data)
                stream.flush()
                os.fsync(stream.fileno())
            path.chmod(0o400)
            fd = os.open(self.root, os.O_RDONLY)
            try:
                os.fsync(fd)
            finally:
                os.close(fd)
        return ref

    def record(self, tx, ref, *, lock=False):
        result = row(
            tx.connection.execute(
                "SELECT * FROM vnext.artifact WHERE tenant_id=%s AND project_id=%s AND task_id=%s AND entity_id=%s AND revision=%s"
                + (" FOR UPDATE" if lock else ""),
                (*tx.owner, ref.id, ref.version.root),
            )
        )
        if (
            not result
            or result["sha256"] != ref.sha256.root
            or result["state"] == "tombstoned"
        ):
            raise DomainError("INVALID_REFERENCE", 422)
        return result

    def checked_bytes(self, record):
        try:
            with self._path(record).open("rb") as stream:
                data = stream.read(self.max_bytes + 1)
        except OSError as error:
            raise DomainError("INVALID_REFERENCE", 422) from error
        if (
            len(data) > self.max_bytes
            or len(data) != record["size_bytes"]
            or hashlib.sha256(data).hexdigest() != record["sha256"]
        ):
            raise DomainError("INVALID_REFERENCE", 422)
        return data

    def seal(self, access, task_id, ref):
        require_collector(access)
        with self.uow.transaction(access, task_id, capability="evidence") as tx:
            record = self.record(tx, ref, lock=True)
            capture_disposition(tx, bound_attempt(tx, record["tool_attempt_id"]))
            self.checked_bytes(record)
            if record["state"] == "staged":
                tx.connection.execute(
                    "UPDATE vnext.artifact SET state='sealed' WHERE tenant_id=%s AND project_id=%s AND task_id=%s AND entity_id=%s AND revision=%s",
                    (*tx.owner, ref.id, ref.version.root),
                )
        return ref

    def read(self, access, artifact_id, version):
        located = self.uow.locate_artifact(access, artifact_id, version)
        if located is None:
            raise DomainError("NOT_FOUND_OR_FORBIDDEN")
        with self.uow.transaction(access, located["task_id"]) as tx:
            ref = BlobRef.model_validate(
                {"id": artifact_id, "version": version, "sha256": located["sha256"]}
            )
            try:
                record = self.record(tx, ref)
                if record["state"] != "sealed":
                    raise DomainError("INVALID_REFERENCE", 422)
                data = self.checked_bytes(record)
            except DomainError as error:
                raise DomainError("NOT_FOUND_OR_FORBIDDEN") from error
        return data, "sha-256=" + base64.b64encode(
            hashlib.sha256(data).digest()
        ).decode("ascii")

    def acquire_lease(self, access, task_id, ref, *, lease_owner, seconds=300):
        require_collector(access)
        if (
            not isinstance(lease_owner, str)
            or not 1 <= len(lease_owner) <= 256
            or not 0 < seconds <= 3600
        ):
            raise DomainError("INVALID_SCHEMA", 422)
        with self.uow.transaction(access, task_id, capability="evidence") as tx:
            record = self.record(tx, ref, lock=True)
            capture_disposition(tx, bound_attempt(tx, record["tool_attempt_id"]))
            tx.connection.execute(
                """INSERT INTO vnext.artifact_lease(tenant_id,project_id,task_id,artifact_id,artifact_revision,lease_owner,expires_at,access_level)
                VALUES (%s,%s,%s,%s,%s,%s,clock_timestamp()+%s*interval '1 second',%s)
                ON CONFLICT(tenant_id,project_id,task_id,artifact_id,artifact_revision,lease_owner) DO UPDATE SET expires_at=EXCLUDED.expires_at""",
                (
                    *tx.owner,
                    ref.id,
                    ref.version.root,
                    lease_owner,
                    seconds,
                    record["access_level"],
                ),
            )

    def release_lease(self, access, task_id, ref, *, lease_owner):
        require_collector(access)
        with self.uow.transaction(access, task_id, capability="evidence") as tx:
            record = self.record(tx, ref, lock=True)
            bound_attempt(tx, record["tool_attempt_id"])
            tx.connection.execute(
                "DELETE FROM vnext.artifact_lease WHERE tenant_id=%s AND project_id=%s AND task_id=%s AND artifact_id=%s AND artifact_revision=%s AND lease_owner=%s",
                (*tx.owner, ref.id, ref.version.root, lease_owner),
            )

    def collect_garbage(self, access, task_id, *, older_than, limit=100):
        if (
            older_than.tzinfo is None
            or older_than > datetime.now(timezone.utc)
            or not 1 <= limit <= 1000
        ):
            raise DomainError("INVALID_SCHEMA", 422)
        candidates = []
        with self.uow.transaction(access, task_id, capability="gc") as tx:
            cursor = tx.connection.execute(
                """SELECT * FROM vnext.artifact a WHERE NOT body_removed AND created_at<%s
                AND NOT vnext.artifact_retained(a.tenant_id,a.project_id,a.task_id,a.entity_id,a.revision)
                ORDER BY entity_id,revision LIMIT %s FOR UPDATE""",
                (older_than, limit),
            )
            columns = [c.name for c in cursor.description]
            candidates = [dict(zip(columns, values)) for values in cursor.fetchall()]
            for candidate in candidates:
                if candidate["state"] != "tombstoned":
                    tx.connection.execute(
                        "UPDATE vnext.artifact SET state='tombstoned' WHERE tenant_id=%s AND project_id=%s AND task_id=%s AND entity_id=%s AND revision=%s",
                        (*tx.owner, candidate["entity_id"], candidate["revision"]),
                    )
        # Mark first, then remove: interruption leaves an inaccessible object for retry,
        # never a published reference whose bytes were removed before a failed commit.
        for candidate in candidates:
            self._path(candidate).unlink(missing_ok=True)
        if candidates:
            fd = os.open(self.root, os.O_RDONLY)
            try:
                os.fsync(fd)
            finally:
                os.close(fd)
            with self.uow.transaction(access, task_id, capability="gc") as tx:
                for candidate in candidates:
                    tx.connection.execute(
                        "UPDATE vnext.artifact SET body_removed=true WHERE tenant_id=%s AND project_id=%s AND task_id=%s AND entity_id=%s AND revision=%s AND state='tombstoned' AND NOT body_removed",
                        (*tx.owner, candidate["entity_id"], candidate["revision"]),
                    )
        return [c["entity_id"] for c in candidates]
