import { StrictMode, useEffect, useLayoutEffect, useMemo, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { App, Button, Checkbox, ConfigProvider, Drawer, Select, Tag, Tooltip } from 'antd';
import zhCN from 'antd/locale/zh_CN';
import { ApartmentOutlined, ExperimentOutlined, SettingOutlined, UserOutlined, ControlOutlined } from '@ant-design/icons';
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { getPalette, isPaletteId, makeWorkbenchTheme, palettes, type PaletteId } from '@wuji/theme';
import { canAdmin, changeContext, configure, getState, pending, profileCommand, projects, reset, simulateReload, useStore, type Role } from './store';
import { CreatePage, NewPage, TaskDetail, TasksPage } from './tasks';
import { ModelsPage } from './models';
import { Field } from './ui';
import '@fontsource-variable/inter';
import '@fontsource/ibm-plex-mono/latin-400.css';
import 'antd/dist/reset.css';
import s from './workbench.module.css';
const themeKey='wuji.creation-prototype.theme';
function initialTheme():PaletteId {const requested=new URLSearchParams(location.search).get('theme');if(isPaletteId(requested))return requested;try{const v=localStorage.getItem(themeKey);if(isPaletteId(v))return v;}catch{/* Theme persistence is optional. */}return 'silver';}
function Appearance({children}:{children:(value:PaletteId,set:(p:PaletteId)=>void)=>ReactNode}){const [id,setId]=useState<PaletteId>(initialTheme);const palette=getPalette(id);const theme=useMemo(()=>makeWorkbenchTheme(palette),[palette]);useLayoutEffect(()=>{for(const [k,v]of Object.entries(palette.colors))document.documentElement.style.setProperty('--'+k,v);document.documentElement.style.colorScheme=palette.mode;document.title=`Wuji · 创建工作台 · ${palette.name}`;},[palette]);return <ConfigProvider theme={theme} locale={zhCN}><App>{children(id,p=>{setId(p);try{localStorage.setItem(themeKey,p);}catch{/* Keep the selected theme in memory. */}})}</App></ConfigProvider>;}
function Shell({theme,setTheme}:{theme:PaletteId;setTheme:(p:PaletteId)=>void}) {const state=useStore();const [settings,setSettings]=useState(false);const navigate=useNavigate();const location=useLocation();const {modal,message}=App.useApp();useEffect(()=>{document.getElementById('content')?.focus();},[location.pathname]);
 return <div className={s.shell}><a className={s.skip} href="#content">跳到主要内容</a><aside className={s.rail}><Link className={s.brand} to="/tasks" aria-label="Wuji 工作台">W<span>·</span></Link><nav aria-label="主要导航"><Tooltip title="任务工作台" placement="right"><Link aria-label="任务工作台" to="/tasks" aria-current={!location.pathname.startsWith('/settings')?'page':undefined}><ApartmentOutlined/></Link></Tooltip>{canAdmin()&&<Tooltip title="模型配置" placement="right"><Link aria-label="模型配置" to="/settings/models" aria-current={location.pathname.startsWith('/settings')?'page':undefined}><ControlOutlined/></Link></Tooltip>}</nav><Tooltip title="演示设置" placement="right"><Button type="text" className={s.railSettings} icon={<SettingOutlined/>} aria-label="演示设置" onClick={()=>setSettings(true)}/></Tooltip></aside>
 <div className={s.workspace}><header className={s.topbar}><div className={s.projectBar}><strong>WUJI</strong><span className={s.divider}>/</span><Select className={s.projectSelect} variant="borderless" aria-label="当前项目" value={state.project} options={projects.map(p=>({value:p.id,label:p.name}))} onChange={value=>{changeContext(state.role,value);navigate('/tasks');}}/></div><div className={s.headerActions}><Select className={s.themeSelect} aria-label="工作台配色" value={theme} virtual={false} options={palettes.map(p=>({value:p.id,label:p.name}))} onChange={setTheme}/><Tag>演示</Tag><Tooltip title={state.role==='both'?'管理员兼操作员':state.role}><span className={s.avatar}><UserOutlined/></span></Tooltip></div></header>
 <main id="content" tabIndex={-1} className={s.main}><Routes><Route path="/" element={<Navigate to="/tasks" replace/>}/><Route path="/tasks" element={<TasksPage/>}/><Route path="/tasks/new" element={<NewPage/>}/><Route path="/drafts/:id" element={<CreatePage/>}/><Route path="/tasks/:id" element={<TaskDetail/>}/><Route path="/settings/models" element={<ModelsPage/>}/><Route path="*" element={<Navigate to="/tasks" replace/>}/></Routes></main><footer className={s.statusbar}><span><span className={s.smallDot}/> 本地工作台</span><span>任务创建 · 模型配置</span></footer></div>
 <Drawer title={<span><ExperimentOutlined/> 演示设置</span>} open={settings} size={380} onClose={()=>setSettings(false)}><div className={s.drawerForm}><p className={s.muted}>本原型只使用本次页面内存，不连接平台、模型或测试目标。真实刷新重置演示，只有主题偏好保留。</p><Field label="演示身份"><Select virtual={false} value={state.role} options={[{value:'both',label:'管理员兼操作员'},{value:'operator',label:'Operator（无模型管理权限）'},{value:'viewer',label:'Viewer（只读项目）'},{value:'admin',label:'TenantAdmin（无项目权限）'},{value:'signed-out',label:'已退出身份'}]} onChange={(value:Role)=>{changeContext(value);setSettings(false);navigate(value==='admin'?'/settings/models':'/tasks');}}/></Field><Field label="下一次任务创建"><Select virtual={false} value={state.createMode} options={[{value:'success',label:'正常返回'},{value:'lost',label:'已创建，但响应丢失'},{value:'reject',label:'明确拒绝，未创建任务'}]} onChange={value=>configure({createMode:value})}/></Field><Checkbox checked={state.queryMiss} onChange={e=>configure({queryMiss:e.target.checked})}>下一次提交首次核对查无回执（404）</Checkbox><Button disabled={!pending()} onClick={()=>{simulateReload();setSettings(false);void message.info('原请求已丢弃，保留原标识进行只读核对');}}>模拟刷新：丢弃原请求</Button><hr className={s.ruleDivider}/><Checkbox checked={state.serviceLost} onChange={e=>configure({serviceLost:e.target.checked})}>下一次服务保存响应丢失</Checkbox><Checkbox checked={state.checkUnknown} onChange={e=>configure({checkUnknown:e.target.checked})}>模型检查结果不明</Checkbox><Checkbox checked={state.blockPending} onChange={e=>configure({blockPending:e.target.checked})}>安全撤销后网关阻断待确认</Checkbox><Button disabled={!canAdmin()||!state.profiles.some(p=>p.state==='revoked'&&p.block==='pending')} onClick={()=>{getState().profiles.filter(p=>p.state==='revoked').forEach(p=>profileCommand(p.id,'confirm-block'));void message.success('已模拟网关阻断确认');}}>模拟网关阻断确认</Button><hr className={s.ruleDivider}/><Button danger onClick={()=>modal.confirm({title:'重置本次演示？',content:'清除内存中的草稿、任务和配置，恢复初始示例；主题保留。',okText:'重置演示',cancelText:'返回',onOk:()=>{reset();setSettings(false);navigate('/tasks');}})}>重置演示数据</Button></div></Drawer>
 </div>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><Appearance>{(theme,setTheme)=><Shell theme={theme} setTheme={setTheme}/>}</Appearance></BrowserRouter></StrictMode>);
