import { useState } from 'react';
import { Alert, App, Button, Collapse, Drawer, Input, InputNumber, Select, Tabs, Tag } from 'antd';
import { PlusOutlined, CopyOutlined, CheckCircleOutlined } from '@ant-design/icons';
import { cacheLabel, pricingIssues, profileLabel, type Pricing, type Profile, type ProfileConfig, type Service } from './domain';
import { addProfile, beginService, canAdmin, checkProfile, profileCommand, resolveService, useStore } from './store';
import { ErrorList, Field, ModelStatus, PriceSummary } from './ui';
import { AccessDenied } from './tasks';
import s from './workbench.module.css';
const nativeBase={tenant_id:'10000000-0000-4000-8000-000000000001',state_revision:1,created_at:'',sync_state:'synced' as const,state:'draft' as const};
function ServiceForm({copy,onClose}:{copy?:Service;onClose:()=>void}) {
 const state=useStore();const [name,setName]=useState(copy?.name??'');const [protocol,setProtocol]=useState<'openai'|'anthropic'>(copy?.config.protocol??'openai');const [base,setBase]=useState(copy?.config.base_url??'');const [key,setKey]=useState('');const [errors,setErrors]=useState<string[]>([]);const {message}=App.useApp();const locked=!!state.servicePending;
 const save=async()=>{const problems:string[]=[];if(!name.trim())problems.push('请填写服务名称');try{const u=new URL(base);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)throw Error();}catch{problems.push('请填写不含凭据、查询参数或片段的 HTTPS Base URL');}if(!key||key!==key.trim()||/[\x00-\x1f]/.test(key)||key.startsWith('os.environ/'))problems.push('请重新输入有效的 API Key，不能使用掩码或环境变量引用');if(/^\*+$/.test(key))problems.push('请填写实际 API Key，不能提交掩码');setErrors(problems);if(problems.length)return;
 const version:Service={...nativeBase,id:crypto.randomUUID(),definition_id:copy?.definition_id??crypto.randomUUID(),kind:'service',number:copy?Math.max(...state.services.filter(v=>v.definition_id===copy.definition_id).map(v=>v.number))+1:1,name:name.trim(),created_at:new Date().toISOString(),config:{protocol,base_url:base.replace(/\/$/,'')},keyConfigured:true};
 // The demo server records only configuration presence, never a credential value.
 const success=await beginService(version);if(success){setKey('');void message.success('服务版本已保存，密钥输入已清除');onClose();}};
 return <div className={s.drawerForm}>{copy&&<Alert type="info" title={`基于 ${copy.name} · V${copy.number} 新建版本`} description="名称、协议和地址已带出，请重新输入 API Key。"/>}<Field label="服务名称" required><Input maxLength={120} disabled={locked} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="协议" required><Select disabled={locked} value={protocol} onChange={setProtocol} options={[{value:'openai',label:'OpenAI 兼容'},{value:'anthropic',label:'Anthropic'}]}/></Field><Field label="Base URL" required hint="模型服务地址由平台允许范围约束。"><Input disabled={locked} value={base} placeholder="https://gateway.example.test/api/openai" onChange={e=>setBase(e.target.value)}/></Field><Field label="API Key" required hint="新版本必须重新输入，不继承旧密钥。确认保存成功后清空。"><Input.Password disabled={locked} autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/></Field><ErrorList items={errors}/>
 {state.servicePending&&<Alert type="warning" title={state.servicePending.state==='submitting'?'服务正在保存':'保存结果待确认'} description="保留原操作标识，先核对结果。" action={state.servicePending.state==='unknown'?<Button onClick={async()=>{if(await resolveService()){setKey('');onClose();void message.success('已核对到原服务版本');}}}>核对服务结果</Button>:undefined}/>}
 <div className={s.drawerFooter}><Button onClick={()=>{setKey('');onClose();}}>关闭</Button><Button type="primary" disabled={locked} loading={state.servicePending?.state==='submitting'} onClick={()=>void save()}>保存服务版本</Button></div></div>;
}
type PriceEdit=Omit<Pricing,'cache_mode'>&{cache_mode:Pricing['cache_mode']|''};
const blankPrice=():PriceEdit=>({source:'',input_per_million:'',output_per_million:'',cache_mode:'',cache_read_per_million:null,cache_creation_per_million:null});
function ProfileForm({copy,onClose}:{copy?:Profile;onClose:()=>void}) {
 const state=useStore();const [name,setName]=useState(copy?.name??'');const [service,setService]=useState(copy?.config.service_version_id??(state.services.length===1?state.services[0]!.id:undefined));const [modelId,setModelId]=useState(copy?.config.model_id??'');const [context,setContext]=useState<number|null>(copy?.config.context_window??null);const [output,setOutput]=useState<number|null>(copy?.config.max_output_tokens??null);const [timeout,setTimeoutValue]=useState<number|null>(copy?.config.timeout_seconds??30);const [priced,setPriced]=useState(!!copy?.config.pricing);const [price,setPrice]=useState<PriceEdit>(copy?.config.pricing?structuredClone(copy.config.pricing):blankPrice());const [errors,setErrors]=useState<string[]>([]);const {message}=App.useApp();
 const save=()=>{const problems:string[]=[];if(!name.trim())problems.push('请填写方案名称');if(!service)problems.push('请选择服务版本');if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]*$/.test(modelId))problems.push('请填写有效的模型 ID');if(context!==null&&(!Number.isSafeInteger(context)||context<1))problems.push('上下文容量必须为正整数');if(output!==null&&(!Number.isSafeInteger(output)||output<1))problems.push('单次输出上限必须为正整数');if(context&&output&&output>context)problems.push('单次输出上限不能超过上下文容量');if(!timeout||timeout<1||timeout>60)problems.push('请求超时必须为 1–60 秒');if(priced)problems.push(...pricingIssues(price as Pricing));setErrors(problems);if(problems.length)return;
 const config:ProfileConfig={service_version_id:service!,model_id:modelId,context_window:context,max_output_tokens:output,timeout_seconds:timeout!,pricing:priced?{...price,cache_mode:price.cache_mode as Pricing['cache_mode']}:null};
 addProfile({...nativeBase,id:crypto.randomUUID(),definition_id:copy?.definition_id??crypto.randomUUID(),kind:'profile',number:copy?Math.max(...state.profiles.filter(v=>v.definition_id===copy.definition_id).map(v=>v.number))+1:1,name:name.trim(),config,created_at:new Date().toISOString(),check:'never',block:'none'});void message.success('方案版本已保存，请单独执行检查后再发布');onClose();};
 const modeLabel=!priced?'未配置价格':!price.cache_mode?'未选择（需要明确确认）':cacheLabel(price as Pricing);
 return <div className={s.drawerForm}>{copy&&<Alert type="info" title={`基于 ${profileLabel(copy)} 新建版本`} description="带出原配置与计价，新版本需要重新检查。"/>}<Field label="方案名称" required><Input maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="服务版本" required hint="引用已有服务版本，无需重新输入 Key。"><Select virtual={false} value={service} placeholder="请选择服务版本" options={state.services.map(v=>({value:v.id,label:`${v.name} · V${v.number}`}))} onChange={setService}/></Field><Field label="模型 ID" required><Input maxLength={255} placeholder="例如 qwen-flash" value={modelId} onChange={e=>setModelId(e.target.value)}/></Field><div className={s.formGrid}><Field label="上下文容量（Token）" hint="发布前需要填写"><InputNumber min={1} precision={0} value={context} onChange={setContext}/></Field><Field label="单次输出上限（Token）" hint="不能超过上下文容量"><InputNumber min={1} precision={0} value={output} onChange={setOutput}/></Field></div>
 <div className={s.sectionHeading}><h2>模型单价</h2>{priced?<Button type="link" onClick={()=>{setPriced(false);setPrice(blankPrice());}}>清除价格，暂不配置</Button>:<Button onClick={()=>setPriced(true)}>配置价格</Button>}</div>
 {!priced?<p className={s.hint}>未配置价格时可以保存和检查，暂不能发布。</p>:<><Field label="价格来源" required><Input maxLength={500} placeholder="公司网关价目表、合同或内部计价说明" value={price.source} onChange={e=>setPrice({...price,source:e.target.value})}/></Field><div className={s.formGrid}><Field label="输入单价（USD／百万 Token）" required><Input inputMode="decimal" value={price.input_per_million} placeholder="填写单价" onChange={e=>setPrice({...price,input_per_million:e.target.value})}/></Field><Field label="输出单价（USD／百万 Token）" required><Input inputMode="decimal" value={price.output_per_million} placeholder="填写单价" onChange={e=>setPrice({...price,output_per_million:e.target.value})}/></Field></div></>}
 <div className={s.priceSummary}><strong>缓存计价：{modeLabel}</strong>{priced&&<span>价格来源：{price.source||'尚未填写'}</span>}</div>
 <Collapse ghost items={[{key:'advanced',label:'高级配置 · 缓存计价与超时',children:<>{priced&&<><Field label="缓存计价模式" required><Select virtual={false} placeholder="请选择，不自动采用默认值" value={price.cache_mode||undefined} options={[{value:'standard_input',label:'按普通输入单价计费'},{value:'separate',label:'单独计价'}]} onChange={v=>setPrice({...price,cache_mode:v,cache_read_per_million:null,cache_creation_per_million:null})}/></Field>{price.cache_mode==='separate'&&<div className={s.formGrid}><Field label="缓存读取单价（USD／百万 Token）" required><Input inputMode="decimal" value={price.cache_read_per_million??''} onChange={e=>setPrice({...price,cache_read_per_million:e.target.value})}/></Field><Field label="缓存创建单价（USD／百万 Token）" required><Input inputMode="decimal" value={price.cache_creation_per_million??''} onChange={e=>setPrice({...price,cache_creation_per_million:e.target.value})}/></Field></div>}</>}<Field label="请求超时（秒）"><InputNumber min={1} max={60} precision={0} value={timeout} onChange={setTimeoutValue}/></Field></>}]} />
 <ErrorList items={errors}/><div className={s.drawerFooter}><Button onClick={onClose}>关闭</Button><Button type="primary" onClick={save}>保存方案版本</Button></div></div>;
}
export function ModelsPage(){const state=useStore();const [tab,setTab]=useState('profiles');const [editor,setEditor]=useState<{kind:'service';copy?:Service}|{kind:'profile';copy?:Profile}|null>(null);const {modal,message}=App.useApp();if(!canAdmin())return <AccessDenied/>;
 const publish=(p:Profile)=>{const issues=[];if(p.check!=='succeeded')issues.push('此版本尚未完成明确成功的连接检查');if(!p.config.pricing)issues.push('请补充价格信息');if(!p.config.context_window||!p.config.max_output_tokens)issues.push('请补充上下文容量与输出上限');if(issues.length){void message.warning(issues.join('；'));return;}profileCommand(p.id,'publish');void message.success('模型方案已发布');};
 return <><div className={s.pageHeading}><div><span className={s.breadcrumb}>组织设置 / 模型配置</span><h1>模型配置</h1></div><Button type="primary" icon={<PlusOutlined/>} disabled={tab==='services'&&!!state.servicePending} onClick={()=>setEditor({kind:tab==='services'?'service':'profile'})}>{tab==='services'?'添加模型服务':'添加模型方案'}</Button></div>
 {state.servicePending&&<Alert type="warning" showIcon title="服务保存结果待确认" description="请先核对原操作，再创建其他服务版本。" action={<Button disabled={state.servicePending.state==='submitting'} onClick={async()=>{if(await resolveService())void message.success('已核对到原服务版本');}}>核对服务结果</Button>}/>}
 <div className={s.listPanel}><Tabs activeKey={tab} onChange={setTab} items={[{key:'profiles',label:'模型方案'},{key:'services',label:'模型服务'}]}/>
 {tab==='services'?<div className={s.modelRows}>{state.services.map(v=><article className={s.modelRow} key={v.id}><div><h2>{v.name} <Tag>V{v.number}</Tag></h2><p><Tag>{v.config.protocol==='openai'?'OpenAI 兼容':'Anthropic'}</Tag><code>{v.config.base_url}</code></p><span className={s.muted}><CheckCircleOutlined/> 密钥已配置</span></div><Button icon={<CopyOutlined/>} disabled={!!state.servicePending} onClick={()=>setEditor({kind:'service',copy:v})}>新建服务版本</Button></article>)}</div>
 :<div className={s.modelRows}>{state.profiles.map(p=><article className={s.modelRow} key={p.id}><div className={s.modelMain}><div className={s.modelHeading}><h2>{p.name} <Tag>V{p.number}</Tag></h2><div><ModelStatus profile={p}/>{['published','retired'].includes(p.state)&&['checking','unknown','failed'].includes(p.check)&&<Tag color="warning">{p.check==='checking'?'检查中':p.check==='unknown'?'检查结果待确认':'检查失败'}</Tag>}</div></div><p><code>{p.config.model_id}</code><span className={s.muted}> · {state.services.find(v=>v.id===p.config.service_version_id)?.name} · 上下文 {p.config.context_window?.toLocaleString()??'未填写'} / 输出 {p.config.max_output_tokens?.toLocaleString()??'未填写'}</span></p><PriceSummary profile={p}/>
 {p.state==='revoked'&&<p className={s.hint}>此版本已不能用于创建任务；不据此判断在途调用是否停止。</p>}
 <div className={s.actions}>{p.state!=='revoked'&&<><Button loading={p.check==='checking'} onClick={()=>void checkProfile(p.id)}>{p.check==='unknown'?'重新检查':'连接检查'}</Button>{p.check==='unknown'&&<Button onClick={()=>void message.info('原检查结果仍待确认，未发起新的检查。')}>核对检查结果</Button>}{p.state==='published'?<Button onClick={()=>profileCommand(p.id,'retire')}>停止发布</Button>:<Button type="primary" onClick={()=>publish(p)}>发布方案</Button>}<Button danger type="text" onClick={()=>modal.confirm({title:'安全撤销此方案版本？',content:'平台将立即禁用此版本，再请求网关阻断。不能据此确认全部在途调用已停止。',okText:'确认安全撤销',cancelText:'返回',onOk:()=>profileCommand(p.id,'revoke')})}>安全撤销</Button></>}
 <Button type="text" icon={<CopyOutlined/>} onClick={()=>setEditor({kind:'profile',copy:p})}>新建方案版本</Button></div></div></article>)}</div>}</div>
 <Drawer title={editor?.kind==='service'?'模型服务版本':'模型方案版本'} open={!!editor} size={640} destroyOnHidden onClose={()=>setEditor(null)}>{editor?.kind==='service'?<ServiceForm copy={editor.copy} onClose={()=>setEditor(null)}/>:editor?.kind==='profile'?<ProfileForm copy={editor.copy} onClose={()=>setEditor(null)}/>:null}</Drawer></>;
}
