import { useEffect, useRef, useState } from 'react';
import { Alert, App, Button, Checkbox, Collapse, DatePicker, Empty, Input, InputNumber, Select, Steps, Tabs, Tag, Tooltip } from 'antd';
import { ArrowLeftOutlined, ArrowRightOutlined, PlusOutlined, DeleteOutlined, SaveOutlined, SafetyCertificateOutlined, FileTextOutlined } from '@ant-design/icons';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import dayjs from 'dayjs';
import { available, creationIssues, isIP, pair, pairLabel, profileLabel, scenarios, scopeIssues, type Draft, type Pair, type Scenario } from './domain';
import { canRead, canWrite, cancelTask, currentUser, inspectList, newDraft, pending, restoreGoal, saveDraft, setEntry, submit, switchScenario, updateContent, updateDraft, useStore } from './store';
import { DraftSummary, ErrorList, Field, getModel, GoalSummary, ModelStatus, PendingNotice, PriceSummary, ScopeSummary } from './ui';
import s from './workbench.module.css';
export function AccessDenied(){return <div className={s.emptyPanel}><Empty description="当前身份没有此项目的操作权限"/></div>;}
function MissingDemo(){return <div className={s.emptyPanel}><Empty description="演示内容不存在或已重置"/><Link to="/tasks">返回任务列表</Link></div>;}
export function TasksPage(){const state=useStore();const navigate=useNavigate();const [tab,setTab]=useState('tasks');const [search,setSearch]=useState('');const tasks=state.tasks.filter(t=>t.projectId===state.project&&t.draft.content.name?.includes(search));const drafts=state.drafts.filter(d=>d.projectId===state.project&&d.userId===currentUser()&&d.content.name?.includes(search));
 useEffect(()=>{inspectList();},[state.project]);if(!canRead())return <AccessDenied/>;
 return <><div className={s.pageHeading}><div><span className={s.breadcrumb}>作业 / 任务</span><h1>任务工作台</h1></div><Button type="primary" icon={<PlusOutlined/>} disabled={!canWrite()||!!pending()} onClick={()=>{const d=newDraft();navigate(`/drafts/${d.id}`);}}>创建任务</Button></div><PendingNotice/>
 <div className={s.listPanel}><div className={s.listTools}><Tabs activeKey={tab} onChange={setTab} items={[{key:'tasks',label:`任务 ${tasks.length}`},{key:'drafts',label:`草稿 ${drafts.length}`}]} /><Input aria-label="搜索任务" className={s.search} placeholder="搜索任务名称" value={search} onChange={e=>setSearch(e.target.value)} allowClear/></div>
 {tab==='tasks'?(tasks.length?<div className={s.tableScroll}><table><thead><tr><th>任务名称</th><th>测试对象</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td><Link to={`/tasks/${t.id}`}><strong>{t.draft.content.name}</strong></Link><small>Web 单点渗透</small></td><td><code>{'entry_url' in t.draft.content?t.draft.content.entry_url:''}</code></td><td><Tag>{t.state==='ready'?'待启动':'已取消'}</Tag></td><td>{new Date(t.createdAt).toLocaleString('zh-CN')}</td><td><Button type="link" onClick={()=>navigate(`/tasks/${t.id}`)}>查看任务</Button></td></tr>)}</tbody></table></div>:<div className={s.emptyPanel}><FileTextOutlined className={s.emptyIcon}/><h2>从一个明确的测试目标开始</h2><p>创建任务，确认测试范围与模型预算。</p><Button disabled={!canWrite()||!!pending()} onClick={()=>{const d=newDraft();navigate(`/drafts/${d.id}`);}}>创建第一个任务</Button></div>)
 :(drafts.length?<div className={s.tableScroll}><table><thead><tr><th>草稿名称</th><th>场景</th><th>保存状态</th><th>操作</th></tr></thead><tbody>{drafts.map(d=><tr key={d.id}><td><strong>{d.content.name||'未命名草稿'}</strong></td><td>{scenarios.find(x=>x.value===d.content.scenario)?.name}</td><td>{d.dirty?'有未保存修改':`已保存 · ${new Date(d.savedAt!).toLocaleTimeString('zh-CN')}`}</td><td><Button type="link" onClick={()=>navigate(`/drafts/${d.id}`)}>继续填写</Button></td></tr>)}</tbody></table></div>:<div className={s.emptyPanel}><Empty description="尚无草稿"/></div>)}</div></>;
}
export function NewPage(){const navigate=useNavigate();const started=useRef(false);useEffect(()=>{if(!started.current&&canWrite()&&!pending()){started.current=true;const d=newDraft();navigate(`/drafts/${d.id}`,{replace:true});}},[navigate]);return <AccessDenied/>;}
function ScopeEditor({draft:d}:{draft:Draft}) {
 const pairs=[...new Set(d.includes.map(pair))];
 return <><div className={s.sectionHeading}><div><h2>包含对象</h2><p>只测试这里明确列出的主机和端口。</p></div><Button icon={<PlusOutlined/>} onClick={()=>updateDraft(d.id,{includes:[...d.includes,{id:crypto.randomUUID(),host:'',descendants:false,scheme:'https',port:443}]},true)}>添加对象</Button></div>
 {d.includes.map((r,i)=><div className={s.rule} key={r.id}><div className={s.ruleFields}><Field label={`包含主机 ${i+1}`} required><Input value={r.host} placeholder="app.example.com 或 IP" onChange={e=>updateDraft(d.id,{includes:d.includes.map(x=>x.id===r.id?{...x,host:e.target.value,descendants:isIP(e.target.value)?false:x.descendants}:x)},true)}/></Field><Field label={`协议 ${i+1}`}><Select value={r.scheme} options={[{value:'https',label:'HTTPS'},{value:'http',label:'HTTP'}]} onChange={v=>updateDraft(d.id,{includes:d.includes.map(x=>x.id===r.id?{...x,scheme:v}:x)},true)}/></Field><Field label={`端口 ${i+1}`}><InputNumber min={1} max={65535} precision={0} value={r.port||null} onChange={v=>updateDraft(d.id,{includes:d.includes.map(x=>x.id===r.id?{...x,port:v??0}:x)},true)}/></Field><Button type="text" aria-label={`移除包含对象 ${i+1}`} icon={<DeleteOutlined/>} onClick={()=>updateDraft(d.id,{includes:d.includes.filter(x=>x.id!==r.id)},true)}/></div>
 {!isIP(r.host)&&<Checkbox checked={r.descendants} onChange={e=>updateDraft(d.id,{includes:d.includes.map(x=>x.id===r.id?{...x,descendants:e.target.checked}:x)},true)}>包含该域名及全部下级子域</Checkbox>}</div>)}
 <div className={s.sectionHeading}><div><h2>排除对象</h2><p>排除优先；新增包含项不会覆盖排除规则。</p></div><Button icon={<PlusOutlined/>} onClick={()=>updateDraft(d.id,{excludes:[...d.excludes,{id:crypto.randomUUID(),host:'',descendants:true,endpoints:'all'}]},true)}>添加排除项</Button></div>
 {d.excludes.length===0?<div className={s.noRules}>无排除项</div>:d.excludes.map((r,i)=><div className={s.rule} key={r.id}><div className={s.excludeFields}><Field label={`排除主机 ${i+1}`} required><Input value={r.host} placeholder="admin.example.com" onChange={e=>updateDraft(d.id,{excludes:d.excludes.map(x=>x.id===r.id?{...x,host:e.target.value,descendants:isIP(e.target.value)?false:x.descendants}:x)},true)}/></Field><Button type="text" aria-label={`移除排除对象 ${i+1}`} icon={<DeleteOutlined/>} onClick={()=>updateDraft(d.id,{excludes:d.excludes.filter(x=>x.id!==r.id)},true)}/></div>
 {!isIP(r.host)&&<Checkbox checked={r.descendants} onChange={e=>updateDraft(d.id,{excludes:d.excludes.map(x=>x.id===r.id?{...x,descendants:e.target.checked}:x)},true)}>同时排除该域名的全部下级子域</Checkbox>}
 <div className={s.hint}>适用范围：{r.endpoints==='all'?'本任务全部已包含协议／端口':r.endpoints.map(pairLabel).join('、')||'未选择组合'}</div>
 <Collapse ghost items={[{key:'pairs',label:'限定排除的协议／端口',children:<><Checkbox checked={r.endpoints==='all'} onChange={e=>updateDraft(d.id,{excludes:d.excludes.map(x=>x.id===r.id?{...x,endpoints:e.target.checked?'all':[]}:x)},true)}>本任务全部已包含协议／端口</Checkbox>{r.endpoints!=='all'&&<Field label={`排除协议端口组合 ${i+1}`} required><Select mode="multiple" virtual={false} placeholder="选择明确组合" value={r.endpoints} options={pairs.map(p=>({value:p,label:pairLabel(p)}))} onChange={(v:Pair[])=>updateDraft(d.id,{excludes:d.excludes.map(x=>x.id===r.id?{...x,endpoints:v}:x)},true)}/></Field>}</>}]} /></div>)}
 <div className={s.sectionHeading}><h2>授权期限</h2></div><Field label="授权截止时间" required hint={`时区：${Intl.DateTimeFormat().resolvedOptions().timeZone}。本次确认仅适用于本任务。`}><DatePicker showTime format="YYYY-MM-DD HH:mm" placeholder="请选择日期和时间" value={d.validUntil?dayjs(d.validUntil):null} disabledDate={date=>date.endOf('day').isBefore(dayjs())} onChange={value=>updateDraft(d.id,{validUntil:value?.toISOString()??''},true)}/></Field>
 <ErrorList items={scopeIssues(d)}/></>;
}
function OtherFields({draft:d}:{draft:Draft}) {const c=d.content;return <>{c.scenario==='ctf'&&<><Field label="题目说明"><Input.TextArea rows={4} value={c.challenge} onChange={e=>updateContent(d.id,{challenge:e.target.value})}/></Field><Field label="靶机入口"><Input value={c.entry_url??''} onChange={e=>updateContent(d.id,{entry_url:e.target.value})}/></Field></>}
 {c.scenario==='comprehensive'&&<><Field label="候选资产（每行一个）"><Input.TextArea rows={4} value={c.assets?.join('\n')} onChange={e=>updateContent(d.id,{assets:e.target.value.split('\n')})}/></Field><Field label="接入条件"><Input.TextArea value={c.access_notes} onChange={e=>updateContent(d.id,{access_notes:e.target.value})}/></Field></>}
 {c.scenario==='exercise'&&<><Field label="单位名称"><Input value={c.organization_name} onChange={e=>updateContent(d.id,{organization_name:e.target.value})}/></Field><Field label="已知域名（每行一个）"><Input.TextArea value={c.known_domains?.join('\n')} onChange={e=>updateContent(d.id,{known_domains:e.target.value.split('\n')})}/></Field></>}
 {c.scenario==='code_audit'&&<><Field label="源码仓库地址"><Input value={c.repository_url??''} onChange={e=>updateContent(d.id,{repository_url:e.target.value})}/></Field><Field label="分支或提交"><Input value={c.revision??''} onChange={e=>updateContent(d.id,{revision:e.target.value})}/></Field></>}
 <Alert type="info" title="此场景可先保存草稿" description="当前仅开放 Web 单点任务创建。"/></>;}
export function CreatePage(){const state=useStore();const {id}=useParams();const navigate=useNavigate();const [search,setSearch]=useSearchParams();const step=Math.max(0,Math.min(3,Number(search.get('step'))||0));const {message}=App.useApp();const d=state.drafts.find(x=>x.id===id&&x.userId===currentUser()&&x.projectId===state.project);if(!canWrite())return <AccessDenied/>;if(!d)return <MissingDemo/>;const p=pending();const locked=!!p;const model=getModel(d);const allIssues=creationIssues(d,state.profiles);const selectStep=(v:number)=>setSearch({step:String(v)});
 const customized=d.content.objective!==d.goalTemplate.objective||d.completionCriteria!==d.goalTemplate.criteria.join('\n');
 const changeType=(value:Scenario)=>{if(value===d.content.scenario||locked)return;switchScenario(d.id,value);selectStep(0);};
 const create=async()=>{const taskId=await submit(d.id);if(taskId)navigate(`/tasks/${taskId}`);};
 return <><div className={s.pageHeading}><div><Link to="/tasks" className={s.back}><ArrowLeftOutlined/> 任务列表</Link><h1>创建任务</h1></div><span className={s.muted}>{d.dirty?'尚未保存修改':`草稿已保存 · ${new Date(d.savedAt!).toLocaleTimeString('zh-CN')}`}</span></div><PendingNotice/>
 {state.outcome?.draftId===d.id&&state.outcome.state==='failed'&&<Alert type="error" showIcon title="创建未成功" description={state.outcome.message}/>}
 <div className={s.createLayout}><div className={s.editor}><div className={s.stepRail}><Steps current={step} size="small" items={['场景与目标','对象与范围','模型与预算','确认并创建'].map((title,i)=>({title,status:i===step?'process' as const:'wait' as const}))} onChange={v=>{if(!locked&&d.content.scenario==='web_single')selectStep(v);}}/></div>
 <fieldset disabled={locked} className={s.stepBody}><div className={locked?s.frozen:''} aria-disabled={locked}>
 {step===0&&<><h2>选择任务类型</h2><div className={s.scenarios}>{scenarios.map(x=><button key={x.value} disabled={locked} type="button" aria-pressed={d.content.scenario===x.value} onClick={()=>changeType(x.value)}><strong>{x.name}</strong><span>{x.hint}</span>{x.value!=='web_single'&&<small>可保存草稿</small>}</button>)}</div>
 {d.content.scenario==='web_single'?<Field label="测试地址（URL）" required hint="默认仅此主机和端口；下一步确认子域、排除项与期限。"><Input placeholder="https://app.example.com" value={d.content.entry_url??''} onChange={e=>setEntry(d.id,e.target.value)}/></Field>:<OtherFields draft={d}/>}
 <Collapse ghost items={[{key:'name',label:d.content.name?`任务名称：${d.content.name}`:'任务名称（可修改）',children:<Field label="任务名称"><Input maxLength={120} placeholder="输入测试地址后自动建议" value={d.content.name} onChange={e=>updateContent(d.id,{name:e.target.value})}/></Field>}]} />
 <div className={s.sectionHeading}><div><h2>任务目标与完成条件</h2><span className={s.hint}>{scenarios.find(x=>x.value===d.content.scenario)?.name} · V{d.goalTemplate.version}{customized?' · 已自定义':' · 默认模板'}</span></div><Button type="text" disabled={locked||!customized} onClick={()=>restoreGoal(d.id)}>恢复默认</Button></div>
 <Field label="任务目标" required><Input.TextArea rows={3} maxLength={8000} value={d.content.objective} onChange={e=>updateContent(d.id,{objective:e.target.value})}/></Field>
 <Field label="完成条件" required><Input.TextArea autoSize={{minRows:4,maxRows:10}} maxLength={20000} value={d.completionCriteria} onChange={e=>updateDraft(d.id,{completionCriteria:e.target.value})}/></Field>
 <Collapse ghost items={[{key:'hints',label:'补充线索（可选）',children:<Field label="补充线索" hint="可填写已知信息、已有尝试或希望关注的功能。"><Input.TextArea rows={3} maxLength={8000} value={d.supplementalHints} onChange={e=>updateDraft(d.id,{supplementalHints:e.target.value})}/></Field>}]} /></>}
 {step===1&&<ScopeEditor draft={d}/>}
 {step===2&&<><h2>模型与预算</h2><p className={s.muted}>选择已发布方案，为本次任务设置金额上限。</p><Field label="模型方案" required><Select virtual={false} placeholder="请选择已发布模型" value={d.content.model_profile_version_id??undefined} options={state.profiles.filter(p=>available(p)||p.id===d.content.model_profile_version_id).map(p=>({value:p.id,label:`${profileLabel(p)}${!available(p)?' · 不可用':''}`,disabled:!available(p)}))} onChange={v=>updateContent(d.id,{model_profile_version_id:v})}/></Field>
 {model?<><ModelStatus profile={model}/><PriceSummary profile={model}/></>:<p className={s.hint}>没有可用模型时仍可保存草稿。</p>}
 {['both','admin'].includes(state.role)?<Link className={s.inlineLink} to="/settings/models">管理模型方案 <ArrowRightOutlined/></Link>:<p className={s.hint}>需要新模型方案时，请联系组织管理员。</p>}
 {model&&!available(model)&&<Alert type="warning" showIcon title="原选择已不可用，请重新选择模型方案"/>}
 <Field label="模型金额上限（USD）" required hint="全部 Agent 与辅助模型调用共用此上限。"><InputNumber<string> stringMode min="0.000001" precision={6} placeholder="填写金额上限" value={d.content.budget_usd??null} onChange={v=>updateContent(d.id,{budget_usd:v})}/></Field>
 <dl className={s.facts}><dt>初始身份</dt><dd>匿名测试</dd><dt>执行能力</dt><dd>暂未开放执行</dd></dl></>}
 {step===3&&<><div className={s.sectionHeading}><h2>确认任务</h2><Tag>Web 单点渗透</Tag></div><h3>{d.content.name||'未命名任务'}</h3><GoalSummary draft={d}/><ScopeSummary draft={d}/><dl className={s.facts}><dt>模型方案</dt><dd>{model?profileLabel(model):'尚未选择'}</dd><dt>模型金额上限</dt><dd>{d.content.budget_usd?`$ ${d.content.budget_usd} USD`:'尚未填写'}</dd></dl>
 <div className={s.confirm}><Checkbox checked={d.confirmed} onChange={e=>updateDraft(d.id,{confirmed:e.target.checked})}>我确认有权对以上包含范围开展测试，并遵守排除项及授权期限</Checkbox></div><ErrorList items={allIssues}/></>}
 </div></fieldset>
 <footer className={s.formFooter}><Button icon={<SaveOutlined/>} disabled={locked} onClick={()=>{saveDraft(d.id);void message.success('草稿已保存');}}>保存草稿</Button><div className={s.actions}>{step>0&&<Button disabled={locked} onClick={()=>selectStep(step-1)}>上一步</Button>}{step<3?<Button type="primary" disabled={locked||d.content.scenario!=='web_single'} onClick={()=>selectStep(step+1)}>下一步 <ArrowRightOutlined/></Button>:<Button type="primary" icon={<SafetyCertificateOutlined/>} loading={p?.state==='submitting'} disabled={locked||allIssues.length>0} onClick={()=>void create()}>确认范围并创建</Button>}</div></footer></div>
 <aside className={s.summary}><DraftSummary draft={d} model={model}/></aside><details className={s.mobileSummary}><summary>查看任务摘要</summary><DraftSummary draft={d} model={model}/></details></div></>;
}
export function TaskDetail(){const state=useStore();const {id}=useParams();const t=state.tasks.find(t=>t.id===id&&t.projectId===state.project);const {modal}=App.useApp();if(!canRead())return <AccessDenied/>;if(!t)return <MissingDemo/>;return <><div className={s.pageHeading}><div><Link to="/tasks" className={s.back}><ArrowLeftOutlined/> 任务列表</Link><h1>{t.draft.content.name}</h1></div><div className={s.actions}><Tag>{t.state==='ready'?'待启动':'已取消'}</Tag><Tooltip title="执行功能尚未开放"><Button disabled>启动</Button></Tooltip>{t.state==='ready'&&<Button disabled={!canWrite()} onClick={()=>modal.confirm({title:'取消此待启动任务？',content:'该任务尚未执行。取消后仍可查看创建配置。',okText:'取消任务',cancelText:'保留任务',onOk:()=>cancelTask(t.id)})}>取消任务</Button>}</div></div>
 <div className={s.detailLayout}><article className={s.editor}><div className={s.stepBody}><GoalSummary draft={t.draft}/><div className={s.targetBar}><code>{'entry_url' in t.draft.content?t.draft.content.entry_url:''}</code><Tag>匿名测试</Tag></div><ScopeSummary draft={t.draft}/><h2>模型与预算</h2><dl className={s.facts}><dt>模型方案</dt><dd>{profileLabel(t.model)}</dd><dt>实际模型</dt><dd><code>{t.model.config.model_id}</code></dd><dt>金额上限</dt><dd>$ {t.draft.content.budget_usd} USD</dd><dt>创建时间</dt><dd>{new Date(t.createdAt).toLocaleString('zh-CN')}</dd></dl><PriceSummary profile={t.model}/></div></article><aside className={s.summary}><h2>任务状态</h2><div className={s.timelineItem}><span className={s.dot}/><div><strong>{t.state==='ready'?'任务已创建':'任务已取消'}</strong><p className={s.muted}>执行尚未开始</p></div></div><p className={s.hint}>创建配置已固定，可在左侧查看授权与预算。</p></aside></div></>;}
