HTTP/1.1 409 Conflict
date: Thu, 17 Sep 2026 04:44:33 GMT
server: uvicorn
content-length: 157
content-type: application/json
cache-control: no-store
x-request-id: d9dee653-c91b-47df-8bae-5464c51468df

{"code":"STALE_EXECUTION","message":"The request could not be completed.","request_id":"d9dee653-c91b-47df-8bae-5464c51468df","retryable":false,"details":{}}