export const snapshot = {
  view_id: 'view-current',
  snapshot_id: 'snapshot-current',
  view_revision: '41',
  query_digest: 'sha256:query-current',
  access_scope_digest: 'sha256:scope-current',
  projection_version: 'topology-v2',
  nodes: [
    {
      id: 'origin:origin-1@1',
      ref: { entity_type: 'origin', id: 'origin-1', revision: '1' },
      display_kind: 'origin',
      label: '授权入口',
      state: 'current',
      allowed_actions: [],
    },
    {
      id: 'goal:goal-1@3',
      ref: { entity_type: 'goal', id: 'goal-1', revision: '3' },
      display_kind: 'goal',
      label: '验证固定目标',
      state: 'unknown',
      allowed_actions: [],
    },
    {
      id: 'observation:observation-1@1',
      ref: { entity_type: 'observation', id: 'observation-1', revision: '1' },
      display_kind: 'observation',
      label: '受信采集记录',
      state: 'complete',
      allowed_actions: [],
    },
    {
      id: 'artifact:artifact-1@7',
      ref: { entity_type: 'artifact', id: 'artifact-1', revision: '7' },
      display_kind: 'artifact',
      label: 'HTTP 响应原文',
      state: 'sealed',
      allowed_actions: [],
    },
    {
      id: 'claim:claim-1@1',
      ref: { entity_type: 'claim', id: 'claim-1', revision: '1' },
      display_kind: 'fact',
      label: '服务返回固定版本',
      state: 'supported',
      allowed_actions: ['inspect'],
    },
    {
      id: 'claim:claim-1@2',
      ref: { entity_type: 'claim', id: 'claim-1', revision: '2' },
      display_kind: 'claim',
      label: '服务可能返回新版本',
      state: 'unassessed',
      allowed_actions: ['inspect'],
    },
    {
      id: 'intent:intent-1@4',
      ref: { entity_type: 'intent', id: 'intent-1', revision: '4' },
      display_kind: 'intent',
      label: '核对版本字段',
      state: 'ready',
      allowed_actions: ['expand'],
    },
    {
      id: 'work_item:work-1@5',
      ref: { entity_type: 'work_item', id: 'work-1', revision: '5' },
      display_kind: 'work_item',
      label: '读取固定响应',
      state: 'settled',
      allowed_actions: [],
    },
    {
      id: 'agent_run:run-1@1',
      ref: { entity_type: 'agent_run', id: 'run-1', revision: '1' },
      display_kind: 'agent_run',
      label: 'Explore 运行',
      state: 'ended',
      allowed_actions: [],
    },
    {
      id: 'verification:verification-1@2',
      ref: { entity_type: 'verification', id: 'verification-1', revision: '2' },
      display_kind: 'verification',
      label: '确定性核验',
      state: 'pass',
      allowed_actions: [],
    },
    {
      id: 'completion_review:review-1@1',
      ref: { entity_type: 'completion_review', id: 'review-1', revision: '1' },
      display_kind: 'completion_review',
      label: '完成检查',
      state: 'wait',
      allowed_actions: [],
    },
    {
      id: 'finding:finding-1@1',
      ref: { entity_type: 'finding', id: 'finding-1', revision: '1' },
      display_kind: 'finding',
      label: '有限结论',
      state: 'partial',
      allowed_actions: [],
    },
    {
      id: 'report:report-1@1',
      ref: { entity_type: 'report', id: 'report-1', revision: '1' },
      display_kind: 'report',
      label: '固定报告',
      state: 'ready',
      allowed_actions: [],
    },
  ],
  edges: [
    {
      id: 'edge:observation-claim-v1',
      source: 'observation:observation-1@1',
      target: 'claim:claim-1@1',
      edge_type: 'supports',
      label: '支持旧修订',
    },
    {
      id: 'edge:claim-v1-intent',
      source: 'claim:claim-1@1',
      target: 'intent:intent-1@4',
      edge_type: 'motivates',
      label: '触发核对',
    },
  ],
  opaque_cursor: 'opaque:current:41',
  truncated: false,
  continuation: null,
  allowed_actions: ['inspect', 'expand'],
} as const;

export const layout = {
  view_name: 'knowledge',
  layout_revision: '17',
  selection_mode: 'explicit_revision',
  entries: [
    {
      anchor: { entity_type: 'claim', id: 'claim-1' },
      x: 640,
      y: 180,
      pinned: true,
    },
    {
      anchor: { entity_type: 'claim', id: 'claim-1', revision: '1' },
      x: 420,
      y: 160,
      pinned: false,
    },
    {
      anchor: { entity_type: 'intent', id: 'intent-1', revision: '4' },
      x: 760,
      y: 320,
      pinned: false,
    },
  ],
  viewport: { x: -92, y: 36, zoom: 0.84 },
} as const;

export const claimBeforeAssessment = {
  ...snapshot,
  nodes: snapshot.nodes.map((node) => node.id === 'claim:claim-1@1'
    ? { ...node, display_kind: 'claim', state: 'unassessed' }
    : node),
};
