/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a non-running vNext task */
        post: operations["createTaskV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a guarded task lifecycle command */
        post: operations["commandTaskV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/claims/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose an unassessed claim */
        post: operations["proposeClaimV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/intents/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose a controlled exploration intent */
        post: operations["proposeIntentV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/work-items/{work_item_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a guarded WorkItem command */
        post: operations["commandWorkItemV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/approvals/{approval_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide a fixed approval request */
        post: operations["decideApprovalV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a qualified assessment */
        post: operations["recordAssessmentV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a stable authorized topology snapshot */
        get: operations["getTaskTopologyV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/views/{view_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream authorized atomic view changes */
        get: operations["streamViewEventsV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List retained authorized snapshots */
        get: operations["listTaskSnapshotsV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/records/{record_type}/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an immutable authorized record revision */
        get: operations["getTaskRecordV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/tasks/{task_id}/layouts/{view_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a versioned personal topology layout */
        put: operations["putTaskLayoutV2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/artifacts/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream authorized immutable artifact bytes */
        get: operations["getArtifactContentV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/archives/{archive_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an imported non-executable archive */
        get: operations["getArchiveV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v2/model/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admit a run-scoped model protocol request */
        post: operations["createModelChatCompletionV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v2/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a trusted capture envelope */
        post: operations["ingestEvidenceV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v2/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive a trusted result envelope */
        post: operations["submitResultV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v2/dispatch/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim work under the current leader epoch */
        post: operations["claimDispatchWorkV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v2/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Prepare one stable worker start operation */
        put: operations["prepareRunV2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v2/runs/{run_id}/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a run control request without implying exit */
        post: operations["controlRunV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RevisionString: string;
        DecimalString: string;
        Sha256Digest: string;
        /** @enum {string} */
        ApiSchemaVersion: "wuji.api.v2";
        /** @enum {string} */
        AssignmentSchemaVersion: "wuji.assignment.v2";
        /** @enum {string} */
        ResultEnvelopeSchemaVersion: "wuji.result-envelope.v2";
        /** @enum {string} */
        AgentPayloadSchemaVersion: "wuji.agent-payload.v2";
        /** @enum {string} */
        ViewEventSchemaVersion: "wuji.view-event.v2";
        /** @enum {string} */
        ViewResetSchemaVersion: "wuji.view-reset.v2";
        /** @enum {string} */
        CaptureSchemaVersion: "wuji.capture.v2";
        /** @enum {string} */
        ClaimKind: "observation-summary" | "hypothesis" | "derived-conclusion";
        /** @enum {string} */
        AssertionRole: "candidate_fact" | "explanation" | "hypothesis";
        /** @enum {string} */
        ProducerKind: "agent" | "human" | "extractor" | "import";
        /** @enum {string} */
        GroundingState: "unchecked" | "linked" | "content_checked" | "invalid";
        /** @enum {string} */
        EvidenceState: "unassessed" | "supported" | "contradicted" | "inconclusive";
        /** @enum {string} */
        ApplicabilityState: "current" | "stale" | "disputed" | "retracted";
        /** @enum {string} */
        AssessmentMethod: "deterministic" | "reproduced_check" | "human_attestation" | "model_review";
        /** @enum {string} */
        WorkKind: "reason" | "explore" | "report";
        /** @enum {string} */
        IntentAcceptance: "proposed" | "admitted" | "rejected" | "superseded";
        /** @enum {string} */
        WorkDesired: "run" | "hold" | "cancel";
        /** @enum {string} */
        WorkState: "ready" | "leased" | "running" | "waiting_input" | "blocked" | "stopping" | "suspended" | "reconciling" | "done" | "failed" | "cancelled";
        /** @enum {string} */
        RunProcessState: "registered" | "starting" | "running" | "stopping" | "exited" | "unknown";
        /** @enum {string} */
        RunResultState: "none" | "received" | "accepted" | "rejected" | "historical_only" | "incomplete";
        /** @enum {string} */
        TaskDesired: "run" | "pause" | "cancel" | "finish";
        /** @enum {string} */
        TaskObserved: "ready" | "running" | "quiescing" | "paused" | "reconciling" | "closed";
        /** @enum {string} */
        CloseTrigger: "goal_satisfied" | "user_cancel" | "budget_exhausted" | "time_limit" | "no_progress" | "system_failure" | "operator_finish";
        /** @enum {string} */
        ResultOutcome: "complete" | "partial" | "inconclusive" | "not_assessed";
        /** @enum {string} */
        GoalStatus: "met" | "not_met" | "unknown" | "not_applicable";
        /** @enum {string} */
        DependencyCondition: "settled" | "accepted_result" | "criterion_satisfied";
        /** @enum {string} */
        RecoveryClass: "settled_boundary" | "approval_boundary" | "non_resumable";
        /** @enum {string} */
        ResultReceiptStatus: "received" | "accepted" | "rejected" | "historical_only";
        /** @enum {string} */
        ComponentReceiptStatus: "accepted_shared" | "accepted_for_check" | "rejected";
        /** @enum {string} */
        EvidenceReceiptStatus: "pending" | "accepted" | "rejected" | "historical_only";
        /** @enum {string} */
        ArtifactState: "staged" | "sealed" | "tombstoned";
        /** @enum {string} */
        EvidenceOrigin: "live_capture" | "fixture_capture" | "imported_unverified";
        /** @enum {string} */
        ModelMode: "synthetic" | "real" | "unknown";
        /** @enum {string} */
        NodeEntityType: "origin" | "goal" | "observation" | "artifact" | "claim" | "intent" | "work_item" | "agent_run" | "verification" | "completion_review" | "finding" | "report";
        /** @enum {string} */
        ReasonDecision: "propose_intents" | "wait" | "propose_completion" | "blocked";
        /** @enum {string} */
        TestResult: "pass" | "fail" | "not_run" | "blocked";
        /** @enum {string} */
        SuspensionCause: "user_hold" | "task_pause" | "completion_epoch" | "scope_revoked";
        /** @enum {string} */
        ReportDeliveryState: "delivery_pending" | "ready" | "incomplete" | "failed";
        /** @enum {string} */
        TaskCommandName: "start" | "pause" | "resume" | "cancel" | "finish";
        /** @enum {string} */
        WorkCommandName: "hold" | "resume" | "cancel";
        /** @enum {string} */
        ApprovalDecisionValue: "approve" | "reject";
        /** @enum {string} */
        CommandDisposition: "accepted" | "rejected" | "already_recorded";
        /** @enum {string} */
        CommandResourceType: "task" | "work_item" | "approval";
        /** @enum {string} */
        ViewMode: "live" | "history";
        /** @enum {string} */
        ViewSelectionMode: "explicit_revision" | "follow_latest";
        /** @enum {string} */
        ViewResetAction: "resnapshot";
        /** @enum {string} */
        ViewPatchOperation: "upsert_node" | "remove_node" | "upsert_edge" | "remove_edge";
        /** @enum {string} */
        CaptureCompleteness: "complete" | "partial" | "unknown";
        /** @enum {string} */
        DispatchStatus: "prepared" | "duplicate" | "rejected";
        /** @enum {string} */
        ControlAction: "stop_after_current" | "stop" | "query";
        /** @enum {string} */
        ControlStatus: "accepted" | "rejected" | "already_recorded";
        /** @enum {string} */
        StartStatus: "prepared" | "running" | "already_recorded" | "rejected" | "unknown";
        /** @enum {string} */
        ScenarioKind: "ctf" | "web_single" | "comprehensive" | "adversary_emulation" | "code_audit";
        /** @enum {string} */
        ErrorCode: "UNAUTHENTICATED" | "FORBIDDEN_COLLECTOR" | "FORBIDDEN_ASSESSOR" | "NOT_FOUND_OR_FORBIDDEN" | "STALE_VERSION" | "STALE_EXECUTION" | "INPUT_DIGEST_CONFLICT" | "OPERATION_UNKNOWN" | "SNAPSHOT_EXPIRED" | "VIEW_EXPIRED" | "HISTORY_UNAVAILABLE" | "INVALID_REFERENCE" | "INVALID_WAIT" | "INVALID_SCHEMA" | "INVALID_SCHEMA_VERSION" | "LIMIT_BLOCKED" | "CAPABILITY_UNAVAILABLE";
        KnowledgeRef: {
            entity_type: components["schemas"]["NodeEntityType"];
            id: string;
            revision: components["schemas"]["RevisionString"];
        };
        ProposalLocalRef: {
            client_ref: string;
        };
        ProposalReference: components["schemas"]["KnowledgeRef"] | components["schemas"]["ProposalLocalRef"];
        CommandResourceRef: {
            entity_type: components["schemas"]["CommandResourceType"];
            id: string;
            revision: components["schemas"]["RevisionString"];
        };
        BlobRef: {
            id: string;
            version: components["schemas"]["RevisionString"];
            sha256: components["schemas"]["Sha256Digest"];
        };
        RunIdentity: {
            tenant_id: string;
            project_id: string;
            task_id: string;
            work_item_id: string;
            agent_run_id: string;
            execution_epoch: components["schemas"]["RevisionString"];
            run_epoch: components["schemas"]["RevisionString"];
            runtime_attempt: components["schemas"]["RevisionString"];
            receiver_id: string;
        };
        ClaimProposal: {
            client_ref: string;
            kind: components["schemas"]["ClaimKind"];
            assertion_role: components["schemas"]["AssertionRole"];
            text: string;
            structured_assertion?: {
                [key: string]: unknown;
            } | null;
            basis_refs: components["schemas"]["ProposalReference"][];
            limitations: string[];
        };
        IntentProposal: {
            client_ref: string;
            question: string;
            basis_refs: components["schemas"]["ProposalReference"][];
            expected_output: string;
        };
        WaitRef: {
            ref: components["schemas"]["ProposalReference"];
            predicate: string;
            predicate_version: components["schemas"]["RevisionString"];
        };
        ReasonDecisionPayload: {
            decision: components["schemas"]["ReasonDecision"];
            wait_refs: components["schemas"]["WaitRef"][];
            reason: string;
        };
        AgentPayload: {
            schema_version: components["schemas"]["AgentPayloadSchemaVersion"];
            claims: components["schemas"]["ClaimProposal"][];
            intent_proposals: components["schemas"]["IntentProposal"][];
            limitations: string[];
            reason_decision?: components["schemas"]["ReasonDecisionPayload"] | null;
        };
        FactAssessment: {
            assessment_id: string;
            claim_ref: components["schemas"]["KnowledgeRef"];
            input_refs: components["schemas"]["KnowledgeRef"][];
            grounding_state: components["schemas"]["GroundingState"];
            evidence_state: components["schemas"]["EvidenceState"];
            applicability_state: components["schemas"]["ApplicabilityState"];
            method_kind: components["schemas"]["AssessmentMethod"];
            method_version: string;
            reviewer_ref: string;
            conditions: string[];
            reason: string;
        } & unknown;
        AssessmentCommand: {
            schema_version: components["schemas"]["ApiSchemaVersion"];
            expected_version: components["schemas"]["RevisionString"];
            assessment: components["schemas"]["FactAssessment"];
        };
        AssessmentReceipt: {
            assessment_id: string;
            revision: components["schemas"]["RevisionString"];
            status: components["schemas"]["ComponentReceiptStatus"];
            claim_ref: components["schemas"]["KnowledgeRef"];
            request_id: string;
            code?: components["schemas"]["ErrorCode"] | null;
        };
        ResultEnvelope: {
            schema_version: components["schemas"]["ResultEnvelopeSchemaVersion"];
            submission_id: string;
            identity: components["schemas"]["RunIdentity"];
            snapshot_id: string;
            read_set: components["schemas"]["KnowledgeRef"][];
            raw_output_ref: components["schemas"]["BlobRef"];
            raw_output_digest: components["schemas"]["Sha256Digest"];
            payload: components["schemas"]["AgentPayload"];
            producer_version: string;
        };
        CaptureEnvelope: {
            schema_version: components["schemas"]["CaptureSchemaVersion"];
            capture_id: string;
            identity: components["schemas"]["RunIdentity"];
            tool_call_id: string;
            tool_attempt_id: string;
            artifact_refs: components["schemas"]["BlobRef"][];
            capture_layer: string;
            /** Format: date-time */
            observed_at: string;
            /** Format: date-time */
            received_at: string;
            evidence_origin: components["schemas"]["EvidenceOrigin"];
            conditions: string[];
            completeness: components["schemas"]["CaptureCompleteness"];
        };
        SessionManifest: {
            session_id: string;
            work_item_id: string;
            checkpoint_revision: components["schemas"]["RevisionString"];
            owner_run_id: string;
            run_epoch: components["schemas"]["RevisionString"];
            history_root: components["schemas"]["BlobRef"];
            message_end: components["schemas"]["RevisionString"];
            provider_state_ref: components["schemas"]["BlobRef"];
            memory_manifest_ref: components["schemas"]["BlobRef"];
            pending_operation_refs: string[];
            lock_digest: components["schemas"]["Sha256Digest"];
            recovery_class: components["schemas"]["RecoveryClass"];
            /** Format: date-time */
            saved_at: string;
        };
        ExecutionLimits: {
            max_work_items: number;
            max_reason_runs: number;
            max_model_requests: number;
            max_tool_calls: number;
            max_single_output_bytes: number;
            max_total_output_bytes: number;
            max_elapsed_seconds: number;
            max_attempts_per_work: number;
            repair_attempts: number;
        };
        WorkerAssignment: {
            schema_version: components["schemas"]["AssignmentSchemaVersion"];
            operation_id: string;
            identity: components["schemas"]["RunIdentity"];
            work_kind: components["schemas"]["WorkKind"];
            snapshot_id: string;
            profile_refs: string[];
            session_manifest_ref: string | null;
            tool_definition_refs: string[];
            limits: components["schemas"]["ExecutionLimits"];
            resume_reason: string | null;
        };
        WorkDependency: {
            predecessor_work_id: string;
            condition: components["schemas"]["DependencyCondition"];
            criterion_ref?: components["schemas"]["KnowledgeRef"] | null;
        };
        WorkItemView: {
            work_item_id: string;
            task_id: string;
            revision: components["schemas"]["RevisionString"];
            kind: components["schemas"]["WorkKind"];
            desired_state: components["schemas"]["WorkDesired"];
            state: components["schemas"]["WorkState"];
            dependencies: components["schemas"]["WorkDependency"][];
            suspension_causes: components["schemas"]["SuspensionCause"][];
            result_state: components["schemas"]["RunResultState"];
            terminal_reason?: string | null;
        };
        GoalCriterionInput: {
            criterion_id: string;
            object: string;
            condition: string;
            evidence_requirements: string[];
            allowed_methods: components["schemas"]["AssessmentMethod"][];
            responsible_party: string;
            required: boolean;
        };
        GoalContractInput: {
            text: string;
            criteria: components["schemas"]["GoalCriterionInput"][];
        };
        AuthorizationScopeEntry: {
            host: string;
            /** @enum {string} */
            protocol: "http" | "https";
            port: number;
        };
        MoneyBudget: {
            amount: components["schemas"]["DecimalString"];
            /** @enum {string} */
            currency: "USD";
        };
        TaskCreate: {
            schema_version: components["schemas"]["ApiSchemaVersion"];
            project_id: string;
            name: string;
            scenario: components["schemas"]["ScenarioKind"];
            goal: components["schemas"]["GoalContractInput"];
            authorization_scope: components["schemas"]["AuthorizationScopeEntry"][];
            /** Format: date-time */
            authorization_expires_at: string;
            model_profile_ref: string;
            runtime_profile_ref: string;
            budget: components["schemas"]["MoneyBudget"];
        };
        TaskView: {
            task_id: string;
            tenant_id: string;
            project_id: string;
            version: components["schemas"]["RevisionString"];
            name: string;
            scenario: components["schemas"]["ScenarioKind"];
            desired_state: components["schemas"]["TaskDesired"];
            observed_state: components["schemas"]["TaskObserved"];
            goal_revision: components["schemas"]["RevisionString"];
            execution_epoch: components["schemas"]["RevisionString"];
            activated_at?: string | null;
            close_trigger?: components["schemas"]["CloseTrigger"] | null;
            result_outcome?: components["schemas"]["ResultOutcome"] | null;
            allowed_actions: components["schemas"]["TaskCommandName"][];
        };
        TaskCommand: {
            schema_version: components["schemas"]["ApiSchemaVersion"];
            command: components["schemas"]["TaskCommandName"];
            expected_version: components["schemas"]["RevisionString"];
            reason: string;
        };
        WorkCommand: {
            schema_version: components["schemas"]["ApiSchemaVersion"];
            command: components["schemas"]["WorkCommandName"];
            expected_version: components["schemas"]["RevisionString"];
            reason: string;
        };
        ApprovalDecision: {
            schema_version: components["schemas"]["ApiSchemaVersion"];
            decision: components["schemas"]["ApprovalDecisionValue"];
            expected_version: components["schemas"]["RevisionString"];
            reason: string;
        };
        CommandReceipt: {
            command_id: string;
            disposition: components["schemas"]["CommandDisposition"];
            resource_ref: components["schemas"]["CommandResourceRef"];
            resource_version: components["schemas"]["RevisionString"];
            request_id: string;
            code?: components["schemas"]["ErrorCode"] | null;
        };
        ComponentReceipt: {
            status: components["schemas"]["ComponentReceiptStatus"];
            local_ref: string;
            request_id: string;
            canonical_ref?: components["schemas"]["KnowledgeRef"] | null;
            code?: components["schemas"]["ErrorCode"] | null;
        };
        ClaimRecord: {
            claim_id: string;
            revision: components["schemas"]["RevisionString"];
            task_id: string;
            kind: components["schemas"]["ClaimKind"];
            assertion_role: components["schemas"]["AssertionRole"];
            text: string;
            structured_assertion?: {
                [key: string]: unknown;
            } | null;
            basis_refs: components["schemas"]["KnowledgeRef"][];
            limitations: string[];
            producer_kind: components["schemas"]["ProducerKind"];
            producer_ref: string;
            /** Format: date-time */
            created_at: string;
            supersedes?: components["schemas"]["KnowledgeRef"] | null;
        };
        ObservationRecord: {
            observation_id: string;
            revision: components["schemas"]["RevisionString"];
            task_id: string;
            capture_id: string;
            tool_attempt_id: string;
            collector_ref: string;
            artifact_refs: components["schemas"]["BlobRef"][];
            capture_layer: string;
            /** Format: date-time */
            observed_at: string;
            /** Format: date-time */
            received_at: string;
            environment_ref: string;
            conditions: string[];
            completeness: components["schemas"]["CaptureCompleteness"];
            evidence_origin: components["schemas"]["EvidenceOrigin"];
        };
        ArtifactRecord: {
            artifact_ref: components["schemas"]["BlobRef"];
            state: components["schemas"]["ArtifactState"];
            media_type: string;
            size_bytes: components["schemas"]["RevisionString"];
            /** Format: date-time */
            created_at: string;
        };
        IntentRecord: {
            intent_id: string;
            revision: components["schemas"]["RevisionString"];
            task_id: string;
            question: string;
            basis_refs: components["schemas"]["KnowledgeRef"][];
            expected_output: string;
            acceptance_state: components["schemas"]["IntentAcceptance"];
            /** Format: date-time */
            created_at: string;
        };
        AgentRunRecord: {
            identity: components["schemas"]["RunIdentity"];
            process_state: components["schemas"]["RunProcessState"];
            result_state: components["schemas"]["RunResultState"];
            model_mode: components["schemas"]["ModelMode"];
            /** Format: date-time */
            created_at: string;
            exited_at?: string | null;
            session_manifest?: components["schemas"]["SessionManifest"] | null;
        };
        GoalRecord: {
            goal_id: string;
            revision: components["schemas"]["RevisionString"];
            text: string;
            status: components["schemas"]["GoalStatus"];
            criterion_refs: components["schemas"]["KnowledgeRef"][];
        };
        GenericRecord: {
            ref: components["schemas"]["KnowledgeRef"];
            title: string;
            summary: string;
            /** Format: date-time */
            created_at: string;
            test_result?: components["schemas"]["TestResult"] | null;
            report_delivery_state?: components["schemas"]["ReportDeliveryState"] | null;
        };
        RecordPayload: components["schemas"]["TaskView"] | components["schemas"]["WorkItemView"] | components["schemas"]["ClaimRecord"] | components["schemas"]["ObservationRecord"] | components["schemas"]["ArtifactRecord"] | components["schemas"]["IntentRecord"] | components["schemas"]["AgentRunRecord"] | components["schemas"]["GoalRecord"] | components["schemas"]["GenericRecord"];
        RecordView: {
            ref: components["schemas"]["KnowledgeRef"];
            display_kind: string;
            record: components["schemas"]["RecordPayload"];
        };
        TopologyNode: {
            id: string;
            ref: components["schemas"]["KnowledgeRef"];
            display_kind: string;
            label: string;
            state?: string | null;
            allowed_actions?: string[];
        };
        TopologyEdge: {
            id: string;
            source: string;
            target: string;
            edge_type: string;
            label?: string | null;
        };
        ViewRemoval: {
            id: string;
        };
        ViewPatchValue: components["schemas"]["TopologyNode"] | components["schemas"]["TopologyEdge"] | components["schemas"]["ViewRemoval"];
        ViewPatch: {
            op: components["schemas"]["ViewPatchOperation"];
            value: components["schemas"]["ViewPatchValue"];
        };
        ViewQuery: {
            mode: components["schemas"]["ViewMode"];
            snapshot_id: string | null;
            cursor: string | null;
            node_limit: number;
            edge_limit: number;
        };
        TopologySnapshot: {
            view_id: string;
            snapshot_id: string;
            view_revision: components["schemas"]["RevisionString"];
            query_digest: string;
            access_scope_digest: string;
            projection_version: string;
            nodes: components["schemas"]["TopologyNode"][];
            edges: components["schemas"]["TopologyEdge"][];
            opaque_cursor: string;
            truncated: boolean;
            continuation: string | null;
            allowed_actions: string[];
        };
        ViewEventBatch: {
            schema_version: components["schemas"]["ViewEventSchemaVersion"];
            view_id: string;
            base_view_revision: components["schemas"]["RevisionString"];
            view_revision: components["schemas"]["RevisionString"];
            cursor: string;
            patches: components["schemas"]["ViewPatch"][];
        };
        ViewReset: {
            schema_version: components["schemas"]["ViewResetSchemaVersion"];
            view_id: string;
            reason: string;
            action: components["schemas"]["ViewResetAction"];
        };
        SnapshotSummary: {
            snapshot_id: string;
            view_id: string;
            view_revision: components["schemas"]["RevisionString"];
            /** Format: date-time */
            created_at: string;
            query_digest: string;
            projection_version: string;
            query?: components["schemas"]["ViewQuery"] | null;
        };
        SnapshotIndex: {
            items: components["schemas"]["SnapshotSummary"][];
            opaque_cursor: string | null;
        };
        LayoutAnchor: {
            entity_type: components["schemas"]["NodeEntityType"];
            id: string;
            revision?: components["schemas"]["RevisionString"] | null;
        };
        LayoutEntry: {
            anchor: components["schemas"]["LayoutAnchor"];
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
            pinned: boolean;
        };
        LayoutPatch: {
            schema_version: components["schemas"]["ApiSchemaVersion"];
            selection_mode: components["schemas"]["ViewSelectionMode"];
            entries: components["schemas"]["LayoutEntry"][];
        };
        LayoutReceipt: {
            view_name: string;
            layout_revision: components["schemas"]["RevisionString"];
            request_id: string;
        };
        ArchiveView: {
            archive_id: string;
            source_version: string;
            /** Format: date-time */
            imported_at: string;
            records: components["schemas"]["RecordView"][];
            /** @constant */
            executable: false;
        };
        EvidenceReceipt: {
            observation_ref: components["schemas"]["KnowledgeRef"] | null;
            capture_id: string;
            status: components["schemas"]["EvidenceReceiptStatus"];
            artifact_refs: components["schemas"]["BlobRef"][];
            request_id: string;
            code?: components["schemas"]["ErrorCode"] | null;
        } & unknown;
        ResultReceipt: {
            submission_id: string;
            status: components["schemas"]["ResultReceiptStatus"];
            components: components["schemas"]["ComponentReceipt"][];
            request_id: string;
            code?: components["schemas"]["ErrorCode"] | null;
        };
        ClaimWork: {
            schema_version: components["schemas"]["ApiSchemaVersion"];
            operation_id: string;
            leader_epoch: components["schemas"]["RevisionString"];
            receiver_id: string;
            capacity_key: string;
        };
        DispatchReceipt: {
            operation_id: string;
            status: components["schemas"]["DispatchStatus"];
            assignment?: components["schemas"]["WorkerAssignment"] | null;
            request_id: string;
            code?: components["schemas"]["ErrorCode"] | null;
        };
        StartReceipt: {
            operation_id: string;
            identity: components["schemas"]["RunIdentity"];
            status: components["schemas"]["StartStatus"];
            process_identity: string | null;
            request_id: string;
        };
        WorkerControl: {
            schema_version: components["schemas"]["ApiSchemaVersion"];
            operation_id: string;
            identity: components["schemas"]["RunIdentity"];
            action: components["schemas"]["ControlAction"];
            reason: string;
        };
        ControlReceipt: {
            operation_id: string;
            identity: components["schemas"]["RunIdentity"];
            status: components["schemas"]["ControlStatus"];
            process_state: components["schemas"]["RunProcessState"];
            request_id: string;
        };
        /** @enum {string} */
        ChatRole: "system" | "user" | "assistant" | "tool";
        ChatMessage: {
            role: components["schemas"]["ChatRole"];
            content?: string | null;
            name?: string | null;
            tool_call_id?: string | null;
            tool_calls?: components["schemas"]["ChatToolCall"][];
        };
        ChatToolCallFunction: {
            name: string;
            arguments: string;
        };
        ChatToolCall: {
            id: string;
            /** @enum {string} */
            type: "function";
            function: components["schemas"]["ChatToolCallFunction"];
        };
        ChatToolDefinition: {
            /** @enum {string} */
            type: "function";
            function: {
                name: string;
                description: string;
                parameters: {
                    [key: string]: unknown;
                };
            };
        };
        ChatCompletionRequest: {
            model: string;
            messages: components["schemas"]["ChatMessage"][];
            tools?: components["schemas"]["ChatToolDefinition"][];
            tool_choice?: ("none" | "auto" | "required") | {
                /** @enum {string} */
                type: "function";
                function: {
                    name: string;
                };
            };
            stream: boolean;
            max_tokens?: number;
            temperature?: number;
        };
        ChatCompletionChoice: {
            index: number;
            message: components["schemas"]["ChatMessage"];
            finish_reason: string | null;
        };
        TokenUsage: {
            prompt_tokens: number;
            completion_tokens: number;
            total_tokens: number;
        };
        ChatCompletionResponse: {
            id: string;
            /** @enum {string} */
            object: "chat.completion";
            created: number;
            model: string;
            choices: components["schemas"]["ChatCompletionChoice"][];
            usage: components["schemas"]["TokenUsage"];
        };
        ErrorResponse: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            request_id: string;
            retryable: boolean;
            details: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Command accepted for authoritative processing */
        CommandAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CommandReceipt"];
            };
        };
        /** @description Proposal component accepted or rejected independently */
        ComponentAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ComponentReceipt"];
            };
        };
        /** @description Missing or invalid authenticated identity */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated principal is not eligible for this operation */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Object is absent or hidden by the current read scope */
        NotFoundOrForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Version, execution, digest, or operation state conflicts */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Requested retained history or view is unavailable */
        Expired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request does not satisfy the versioned input contract */
        InvalidSchema: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description A published hard limit prevents admission */
        LimitBlocked: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Required runtime capability is unavailable */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        IfMatch: components["schemas"]["RevisionString"];
        TrustedRequestId: string;
        TaskId: string;
        WorkItemId: string;
        ApprovalId: string;
        ViewId: string;
        ViewName: string;
        RecordType: components["schemas"]["NodeEntityType"];
        RecordId: string;
        ArtifactId: string;
        ArchiveId: string;
        RunId: string;
        ViewMode: components["schemas"]["ViewMode"];
        SnapshotIdQuery: string;
        ViewCursor: string;
        RevisionQuery: components["schemas"]["RevisionString"];
        ArtifactVersionQuery: components["schemas"]["RevisionString"];
        NodeLimit: number;
        EdgeLimit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createTaskV2: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Task created in the non-running ready state */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    commandTaskV2: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCommand"];
            };
        };
        responses: {
            202: components["responses"]["CommandAccepted"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFoundOrForbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    proposeClaimV2: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimProposal"];
            };
        };
        responses: {
            202: components["responses"]["ComponentAccepted"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFoundOrForbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    proposeIntentV2: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentProposal"];
            };
        };
        responses: {
            202: components["responses"]["ComponentAccepted"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFoundOrForbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    commandWorkItemV2: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                work_item_id: components["parameters"]["WorkItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkCommand"];
            };
        };
        responses: {
            202: components["responses"]["CommandAccepted"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFoundOrForbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    decideApprovalV2: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            202: components["responses"]["CommandAccepted"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFoundOrForbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    recordAssessmentV2: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentCommand"];
            };
        };
        responses: {
            /** @description Assessment recorded for checking or rejected */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentReceipt"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFoundOrForbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    getTaskTopologyV2: {
        parameters: {
            query?: {
                mode?: components["parameters"]["ViewMode"];
                snapshot_id?: components["parameters"]["SnapshotIdQuery"];
                cursor?: components["parameters"]["ViewCursor"];
                node_limit?: components["parameters"]["NodeLimit"];
                edge_limit?: components["parameters"]["EdgeLimit"];
            };
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized stable topology snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologySnapshot"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFoundOrForbidden"];
            410: components["responses"]["Expired"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    streamViewEventsV2: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["ViewCursor"];
            };
            header?: never;
            path: {
                view_id: components["parameters"]["ViewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized SSE stream of atomic view batches or resets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ViewEventBatch"] | components["schemas"]["ViewReset"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFoundOrForbidden"];
            410: components["responses"]["Expired"];
        };
    };
    listTaskSnapshotsV2: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["ViewCursor"];
            };
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized saved snapshot index */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotIndex"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFoundOrForbidden"];
        };
    };
    getTaskRecordV2: {
        parameters: {
            query: {
                revision: components["parameters"]["RevisionQuery"];
            };
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
                record_type: components["parameters"]["RecordType"];
                record_id: components["parameters"]["RecordId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized immutable record revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordView"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFoundOrForbidden"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    putTaskLayoutV2: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                task_id: components["parameters"]["TaskId"];
                view_name: components["parameters"]["ViewName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutPatch"];
            };
        };
        responses: {
            /** @description Updated personal layout revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutReceipt"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFoundOrForbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    getArtifactContentV2: {
        parameters: {
            query: {
                version: components["parameters"]["ArtifactVersionQuery"];
            };
            header?: never;
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized immutable artifact bytes */
            200: {
                headers: {
                    Digest: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFoundOrForbidden"];
        };
    };
    getArchiveV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                archive_id: components["parameters"]["ArchiveId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only imported archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveView"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFoundOrForbidden"];
        };
    };
    createModelChatCompletionV2: {
        parameters: {
            query?: never;
            header: {
                "X-Wuji-Request-ID": components["parameters"]["TrustedRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Admitted model protocol response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatCompletionResponse"];
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
            429: components["responses"]["LimitBlocked"];
            503: components["responses"]["Unavailable"];
        };
    };
    ingestEvidenceV2: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureEnvelope"];
            };
        };
        responses: {
            /** @description Evidence receipt persisted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceReceipt"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    submitResultV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultEnvelope"];
            };
        };
        responses: {
            /** @description Raw result received for component validation */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultReceipt"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    claimDispatchWorkV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimWork"];
            };
        };
        responses: {
            /** @description Atomic dispatch claim receipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchReceipt"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["LimitBlocked"];
        };
    };
    prepareRunV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerAssignment"];
            };
        };
        responses: {
            /** @description Stable start operation receipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartReceipt"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
        };
    };
    controlRunV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerControl"];
            };
        };
        responses: {
            /** @description Control request accepted; this is not an exit receipt */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlReceipt"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidSchema"];
        };
    };
}
